import React,{useEffect,useMemo,useState} from 'react'
import {AlertTriangle,Calendar,ChefHat,ClipboardCheck,Package,RefreshCw,ShoppingCart,Users} from 'lucide-react'
import {Btn,Card,DataTable,Input,KpiCard,Modal,PageHeader,Select,StatusBadge} from '../components/ui'
import {HospitalityOperations,ProductResponse,UserResponse,hospitalityApi,hospitalityOpsApi,productApi,userApi} from '../services/api'

type Tab='FLOOR'|'RESERVATIONS'|'MENU'|'STOCK'|'SHIFTS'|'PURCHASING'|'APPROVALS'|'REPORTS'
const today=()=>new Date().toISOString().slice(0,10)
export default function HospitalityOperationsPage(){
 const [tab,setTab]=useState<Tab>('FLOOR'),[data,setData]=useState<HospitalityOperations|null>(null),[tables,setTables]=useState<any[]>([]),[products,setProducts]=useState<ProductResponse[]>([]),[users,setUsers]=useState<UserResponse[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState('')
 const [tableControl,setTableControl]=useState<any|null>(null),[waiterId,setWaiterId]=useState(''),[mergeId,setMergeId]=useState('')
 const [barControl,setBarControl]=useState<any|null>(null),[barType,setBarType]=useState('WASTAGE'),[barQuantity,setBarQuantity]=useState('1'),[barReason,setBarReason]=useState('')
 const [shiftClose,setShiftClose]=useState<any|null>(null),[actualCash,setActualCash]=useState('0'),[tips,setTips]=useState('0'),[shiftExpenses,setShiftExpenses]=useState('0'),[shiftNotes,setShiftNotes]=useState('')
 const [reservation,setReservation]=useState({tableId:'',customerName:'',customerPhone:'',guestCount:'2',reservedAt:'',notes:''})
 const [ingredient,setIngredient]=useState({name:'',unit:'ML',quantity:'0',reorderLevel:'0',unitCost:'0'})
 const [supplier,setSupplier]=useState({name:'',phone:'',email:'',address:''})
 const [float,setFloat]=useState('0'),[reportDates,setReportDates]=useState({startDate:today(),endDate:today()}),[report,setReport]=useState<any>(null),[reportLoading,setReportLoading]=useState(false)
 const load=async(silent=false)=>{if(!silent)setLoading(true);try{const[o,h,p,u]=await Promise.all([hospitalityOpsApi.dashboard(),hospitalityApi.dashboard(),productApi.list(),userApi.list().catch(()=>null)]);if(o.success)setData(o.data);if(h.success)setTables(h.data?.tables||[]);if(p.success)setProducts(p.data||[]);if(u?.success)setUsers((u.data||[]).filter(user=>user.isActive!==false))}catch(e:any){setMessage(e.response?.data?.message||'Could not load hospitality operations')}finally{if(!silent)setLoading(false)}}
 useEffect(()=>{load();const timer=window.setInterval(()=>load(true),5000);return()=>window.clearInterval(timer)},[])
 const act=async(fn:()=>Promise<any>)=>{setMessage('');try{const r=await fn();setMessage(r.success===false?r.message:'Saved successfully');if(r.success!==false)await load()}catch(e:any){setMessage(e.response?.data?.message||'Request failed')}}
 const bookReservation=()=>{const customerName=reservation.customerName.trim();const guestCount=Number(reservation.guestCount);const reservedAt=reservation.reservedAt?new Date(reservation.reservedAt):null;if(!customerName){setMessage('Customer name is required.');return}if(!reservedAt||Number.isNaN(reservedAt.getTime())){setMessage('Choose a valid reservation date and time.');return}if(!Number.isInteger(guestCount)||guestCount<1||guestCount>100){setMessage('Guests must be a whole number between 1 and 100.');return}act(()=>hospitalityOpsApi.reservation({...reservation,customerName,tableId:reservation.tableId||null,guestCount,reservedAt:reservedAt.toISOString()}))}
 const runReport=async()=>{if(!reportDates.startDate||!reportDates.endDate||reportDates.startDate>reportDates.endDate){setMessage('Choose a valid report date range.');return}setReportLoading(true);setMessage('');try{const r=await hospitalityOpsApi.report(reportDates.startDate,reportDates.endDate);if(r.success===false)throw new Error(r.message||'Could not load report');setReport(r.data)}catch(e:any){setMessage(e.response?.data?.message||e.message||'Could not load report')}finally{setReportLoading(false)}}
 const openShift=data?.shifts.find(s=>s.status==='OPEN'),low=data?.ingredients.filter(i=>i.isLowStock)||[]
 const tabs:Tab[]=['FLOOR','RESERVATIONS','MENU','STOCK','SHIFTS','PURCHASING','APPROVALS','REPORTS']
 return <div className="fade-in" style={{display:'flex',flexDirection:'column',gap:16}}><PageHeader title="Hospitality Operations" action={<Btn variant="secondary" icon={<RefreshCw size={14}/>} onClick={load}>Refresh</Btn>}/>
 {message&&<div style={{padding:11,borderRadius:8,background:'var(--b360-green-bg)',color:'var(--b360-text)',fontSize:13}}>{message}</div>}
 <div style={{display:'flex',gap:6,overflowX:'auto',paddingBottom:4}}>{tabs.map(value=><button key={value} onClick={()=>setTab(value)} style={{border:'1px solid var(--b360-border)',borderRadius:18,padding:'7px 12px',whiteSpace:'nowrap',background:tab===value?'var(--b360-green)':'white',color:tab===value?'white':'inherit',cursor:'pointer'}}>{value.replace('_',' ')}</button>)}</div>
 {loading?<Card style={{padding:35,textAlign:'center'}}>Loading operations…</Card>:!data?<Card style={{padding:25}}>Operations unavailable.</Card>:<>
 {tab==='FLOOR'&&<><div className="responsive-grid responsive-grid-4"><KpiCard title="Tables" value={String(tables.length)} change={`${tables.filter(t=>t.status==='OCCUPIED').length} occupied`} icon={<Users size={18}/>} color="var(--b360-blue)"/><KpiCard title="Reservations" value={String(data.reservations.filter(r=>r.status==='BOOKED').length)} change="Upcoming" icon={<Calendar size={18}/>} color="var(--b360-amber)"/><KpiCard title="Open shift" value={openShift?'Yes':'No'} change={openShift?'Trading active':'Start a shift'} icon={<ClipboardCheck size={18}/>} color="var(--b360-green)"/><KpiCard title="Low ingredients" value={String(low.length)} change="Need purchasing" icon={<AlertTriangle size={18}/>} color="var(--b360-red)"/></div><Card style={{padding:18}}><h3>Floor plan</h3><div style={{position:'relative',minHeight:420,marginTop:12,background:'#F8FAFC',border:'1px dashed var(--b360-border)',borderRadius:12,overflow:'auto'}}>{tables.filter(t=>!t.mergedIntoTableId).map((table,index)=><button key={table.id} onClick={()=>{setTableControl(table);setWaiterId(table.waiterUserId||'');setMergeId('')}} style={{position:'absolute',left:table.positionX??40+(index%5)*150,top:table.positionY??40+Math.floor(index/5)*100,width:120,height:70,border:`2px solid ${table.status==='OCCUPIED'?'var(--b360-amber)':'var(--b360-green)'}`,borderRadius:table.shape==='CIRCLE'?'50%':12,background:'white',cursor:'pointer'}}><b>{table.name}</b><small style={{display:'block'}}>{table.capacity} seats · {table.status}</small></button>)}</div><p style={{fontSize:11,color:'var(--b360-text-secondary)'}}>Select a table to assign a waiter, merge it, or adjust its layout.</p></Card></>}
 {tab==='RESERVATIONS'&&<><Card style={{padding:18}}><h3>New reservation</h3><div className="responsive-grid responsive-grid-3" style={{marginTop:12}}><Select label="Table" value={reservation.tableId} onChange={v=>setReservation({...reservation,tableId:v})} options={[{value:'',label:'Assign later'},...tables.map(t=>({value:t.id,label:t.name}))]}/><Input label="Customer" value={reservation.customerName} onChange={v=>setReservation({...reservation,customerName:v})}/><Input label="Phone" value={reservation.customerPhone} onChange={v=>setReservation({...reservation,customerPhone:v})}/><Input label="Guests" type="number" value={reservation.guestCount} onChange={v=>setReservation({...reservation,guestCount:v})}/><Input label="Date and time" type="datetime-local" value={reservation.reservedAt} onChange={v=>setReservation({...reservation,reservedAt:v})}/><Input label="Notes" value={reservation.notes} onChange={v=>setReservation({...reservation,notes:v})}/></div><Btn onClick={bookReservation}>Book reservation</Btn></Card><DataTable headers={['Time','Customer','Guests','Table','Status','Actions']} rows={data.reservations.map(r=>[new Date(r.reservedAt).toLocaleString('en-KE'),r.customerName,r.guestCount,tables.find(t=>t.id===r.tableId)?.name||'Unassigned',<StatusBadge status={r.status}/>,r.status==='BOOKED'?<div style={{display:'flex',gap:5}}><Btn small onClick={()=>act(()=>hospitalityOpsApi.reservationStatus(r.id,'SEATED'))}>Seat</Btn><Btn small variant="secondary" onClick={()=>act(()=>hospitalityOpsApi.reservationStatus(r.id,'CANCELLED'))}>Cancel</Btn></div>:'—'])}/></>}
 {tab==='MENU'&&<MenuProfiles products={products} data={data} act={act}/>} 
 {tab==='STOCK'&&<><Card style={{padding:18}}><h3>Add ingredient</h3><div className="responsive-grid responsive-grid-4" style={{margin:'12px 0'}}><Input label="Name" value={ingredient.name} onChange={v=>setIngredient({...ingredient,name:v})}/><Input label="Unit" value={ingredient.unit} onChange={v=>setIngredient({...ingredient,unit:v})}/><Input label="Opening quantity" type="number" value={ingredient.quantity} onChange={v=>setIngredient({...ingredient,quantity:v})}/><Input label="Reorder level" type="number" value={ingredient.reorderLevel} onChange={v=>setIngredient({...ingredient,reorderLevel:v})}/><Input label="Unit cost" type="number" value={ingredient.unitCost} onChange={v=>setIngredient({...ingredient,unitCost:v})}/></div><Btn onClick={()=>act(()=>hospitalityOpsApi.ingredient({...ingredient,quantity:Number(ingredient.quantity),reorderLevel:Number(ingredient.reorderLevel),unitCost:Number(ingredient.unitCost)}))}>Add ingredient</Btn></Card><DataTable headers={['Ingredient','Unit','On hand','Reorder','Unit cost','Status','Bar controls']} rows={data.ingredients.map(i=>[i.name,i.unit,i.quantity,i.reorderLevel,`KES ${i.unitCost.toLocaleString()}`,<StatusBadge status={i.isLowStock?'LOW':'ACTIVE'}/>,<Btn small variant="secondary" onClick={()=>{setBarControl(i);setBarType('WASTAGE');setBarQuantity('1');setBarReason('')}}>Record event</Btn>])}/></>}
 {tab==='SHIFTS'&&<><Card style={{padding:18}}>{openShift?<><h3>Close current shift</h3><p>Opened {new Date(openShift.openedAt).toLocaleString('en-KE')} · Float KES {openShift.openingFloat.toLocaleString()}</p><Btn onClick={()=>{setShiftClose(openShift);setActualCash('0');setTips('0');setShiftExpenses('0');setShiftNotes('')}}>Close and reconcile</Btn></>:<><h3>Start shift</h3><div style={{maxWidth:260,margin:'12px 0'}}><Input label="Opening float (KES)" type="number" value={float} onChange={setFloat}/></div><Btn onClick={()=>act(()=>hospitalityOpsApi.openShift({openingFloat:Number(float),notes:''}))}>Open shift</Btn></>}</Card><DataTable headers={['Opened','Closed','Float','Expected cash','Actual cash','M-Pesa','Card','Variance','Status']} rows={data.shifts.map(s=>[new Date(s.openedAt).toLocaleString('en-KE'),s.closedAt?new Date(s.closedAt).toLocaleString('en-KE'):'—',s.openingFloat,s.expectedCash??'—',s.actualCash??'—',s.mpesaTotal??'—',s.cardTotal??'—',s.variance??'—',<StatusBadge status={s.status}/>])}/></>}
 {tab==='PURCHASING'&&<><Card style={{padding:18}}><h3>Add supplier</h3><div className="responsive-grid responsive-grid-4" style={{margin:'12px 0'}}><Input label="Name" value={supplier.name} onChange={v=>setSupplier({...supplier,name:v})}/><Input label="Phone" value={supplier.phone} onChange={v=>setSupplier({...supplier,phone:v})}/><Input label="Email" value={supplier.email} onChange={v=>setSupplier({...supplier,email:v})}/><Input label="Address" value={supplier.address} onChange={v=>setSupplier({...supplier,address:v})}/></div><Btn onClick={()=>act(()=>hospitalityOpsApi.supplier(supplier))}>Add supplier</Btn></Card><DataTable headers={['PO','Supplier','Total','Ordered','Received','Status','Action']} rows={data.purchaseOrders.map(po=>[po.orderNumber,data.suppliers.find(s=>s.id===po.supplierId)?.name||po.supplierId,`KES ${po.totalCost.toLocaleString()}`,new Date(po.orderedAt).toLocaleDateString(),po.receivedAt?new Date(po.receivedAt).toLocaleDateString():'—',<StatusBadge status={po.status}/>,po.status!=='RECEIVED'?<Btn small onClick={()=>act(()=>hospitalityOpsApi.receivePurchaseOrder(po.id))}>Receive goods</Btn>:'—'])}/><p style={{fontSize:12,color:'var(--b360-text-secondary)'}}>Purchase orders can be created through the shared operations API with supplier, ingredient quantities, and unit costs.</p></>}
 {tab==='APPROVALS'&&<DataTable headers={['Action','Entity','Reason','Requested','Status','Decision']} rows={data.approvals.map(a=>[a.actionType,`${a.entityType} · ${a.entityId.slice(0,8)}`,a.reason,new Date(a.requestedAt).toLocaleString('en-KE'),<StatusBadge status={a.status}/>,a.status==='PENDING'?<div style={{display:'flex',gap:5}}><Btn small onClick={()=>act(()=>hospitalityOpsApi.decideApproval(a.id,true))}>Approve</Btn><Btn small variant="danger" onClick={()=>act(()=>hospitalityOpsApi.decideApproval(a.id,false))}>Reject</Btn></div>:'—'])}/>} 
 {tab==='REPORTS'&&<><Card style={{padding:18}}><div style={{display:'flex',gap:10,alignItems:'end',flexWrap:'wrap'}}><Input label="From" type="date" value={reportDates.startDate} onChange={v=>setReportDates({...reportDates,startDate:v})}/><Input label="To" type="date" value={reportDates.endDate} onChange={v=>setReportDates({...reportDates,endDate:v})}/><Btn onClick={runReport} disabled={reportLoading}>{reportLoading?'Loading…':'Run report'}</Btn></div></Card>{report&&<ReportView report={report}/>}</>}
 </>}
 {tableControl&&<Modal title={`Table controls · ${tableControl.name}`} onClose={()=>setTableControl(null)} footer={<><Btn variant="secondary" onClick={()=>setTableControl(null)}>Cancel</Btn><Btn onClick={()=>act(async()=>{const result=await hospitalityOpsApi.table(tableControl.id,{waiterUserId:waiterId||null,mergeIntoTableId:mergeId||null,positionX:tableControl.positionX??40,positionY:tableControl.positionY??40,shape:tableControl.shape||'RECTANGLE'});setTableControl(null);return result})}>Save controls</Btn></>}><div style={{display:'grid',gap:12}}><Select label="Assigned waiter" value={waiterId} onChange={setWaiterId} options={[{value:'',label:'Unassigned'},...users.map(user=>({value:user.id,label:`${user.name} · ${user.role}`}))]}/><Select label="Merge into table" value={mergeId} onChange={setMergeId} options={[{value:'',label:'Do not merge'},...tables.filter(table=>table.id!==tableControl.id&&!table.mergedIntoTableId).map(table=>({value:table.id,label:table.name}))]}/><Select label="Shape" value={tableControl.shape||'RECTANGLE'} onChange={value=>setTableControl({...tableControl,shape:value})} options={[{value:'RECTANGLE',label:'Rectangle'},{value:'CIRCLE',label:'Circle'}]}/><div className="responsive-grid responsive-grid-2"><Input label="Floor X position" type="number" value={String(tableControl.positionX??0)} onChange={value=>setTableControl({...tableControl,positionX:Number(value)})}/><Input label="Floor Y position" type="number" value={String(tableControl.positionY??0)} onChange={value=>setTableControl({...tableControl,positionY:Number(value)})}/></div></div></Modal>}
 {barControl&&<Modal title={`Stock event · ${barControl.name}`} onClose={()=>setBarControl(null)} footer={<><Btn variant="secondary" onClick={()=>setBarControl(null)}>Cancel</Btn><Btn onClick={()=>act(async()=>{const result=await hospitalityOpsApi.barStock({ingredientId:barControl.id,eventType:barType,quantity:Number(barQuantity),unit:barControl.unit,reason:barReason});setBarControl(null);return result})}>Record event</Btn></>}><div style={{display:'grid',gap:12}}><Select label="Event" value={barType} onChange={setBarType} options={['OPEN_BOTTLE','SHOT','WASTAGE','BREAKAGE','SPILLAGE','COMPLIMENTARY','STOCK_IN','VARIANCE'].map(value=>({value,label:value.replace(/_/g,' ')}))}/><Input label={`Quantity (${barControl.unit})`} type="number" value={barQuantity} onChange={setBarQuantity}/><Input label="Reason / reference" value={barReason} onChange={setBarReason}/></div></Modal>}
 {shiftClose&&<Modal title="Close and reconcile shift" onClose={()=>setShiftClose(null)} footer={<><Btn variant="secondary" onClick={()=>setShiftClose(null)}>Cancel</Btn><Btn onClick={()=>act(async()=>{const result=await hospitalityOpsApi.closeShift(shiftClose.id,{actualCash:Number(actualCash),tipsTotal:Number(tips),expensesTotal:Number(shiftExpenses),notes:shiftNotes});setShiftClose(null);return result})}>Close shift</Btn></>}><div style={{display:'grid',gap:12}}><Input label="Actual cash counted (KES)" type="number" value={actualCash} onChange={setActualCash}/><Input label="Tips (KES)" type="number" value={tips} onChange={setTips}/><Input label="Shift expenses (KES)" type="number" value={shiftExpenses} onChange={setShiftExpenses}/><Input label="Reconciliation notes" value={shiftNotes} onChange={setShiftNotes}/></div></Modal>}
 </div>
}
function MenuProfiles({products,data,act}:{products:ProductResponse[];data:HospitalityOperations;act:(fn:()=>Promise<any>)=>void}){
 const [id,setId]=useState(''),[station,setStation]=useState('KITCHEN'),[sold,setSold]=useState(false),[age,setAge]=useState(false),[minimumAge,setMinimumAge]=useState('18'),[happy,setHappy]=useState(''),[happyStart,setHappyStart]=useState('16:00'),[happyEnd,setHappyEnd]=useState('19:00'),[periods,setPeriods]=useState(''),[sizes,setSizes]=useState(''),[extras,setExtras]=useState(''),[variants,setVariants]=useState(''),[combos,setCombos]=useState('')
 const profile=data.menuProfiles.find(p=>p.productId===id)
 const format=(items:Array<{name:string;priceDelta:number}>)=>items.map(item=>`${item.name}:${item.priceDelta}`).join(', ')
 const parse=(value:string)=>value.split(',').map(item=>item.trim()).filter(Boolean).map(item=>{const[name,price='0']=item.split(':');return{name:name.trim(),priceDelta:Number(price)||0}})
 useEffect(()=>{if(profile){setStation(profile.preparationStation||'NONE');setSold(profile.soldOut);setAge(profile.ageRestricted);setMinimumAge(String(profile.minimumAge||18));setHappy(profile.happyHourPrice?.toString()||'');setHappyStart(profile.happyHourStart||'16:00');setHappyEnd(profile.happyHourEnd||'19:00');setPeriods(profile.mealPeriods.join(', '));setSizes(format(profile.sizes));setExtras(format(profile.extras));setVariants(format(profile.variants));setCombos(profile.comboProductIds.join(', '))}else{setStation('KITCHEN');setSold(false);setAge(false);setMinimumAge('18');setHappy('');setHappyStart('16:00');setHappyEnd('19:00');setPeriods('');setSizes('');setExtras('');setVariants('');setCombos('')}},[id])
 return <Card style={{padding:18}}><h3>Menu availability and routing</h3><div className="responsive-grid responsive-grid-3" style={{margin:'12px 0'}}><Select label="Menu item" value={id} onChange={setId} options={[{value:'',label:'Select product'},...products.map(p=>({value:p.id,label:p.name}))]}/><Select label="Preparation station" value={station} onChange={setStation} options={[{value:'KITCHEN',label:'Kitchen'},{value:'BAR',label:'Bar'},{value:'NONE',label:'No preparation ticket'}]}/><Input label="Meal periods (comma separated)" value={periods} onChange={setPeriods}/><Input label="Sizes (Name:price, …)" value={sizes} onChange={setSizes}/><Input label="Extras (Name:price, …)" value={extras} onChange={setExtras}/><Input label="Variants (Name:price, …)" value={variants} onChange={setVariants}/><Input label="Combo product IDs" value={combos} onChange={setCombos}/><Input label="Happy-hour price" type="number" value={happy} onChange={setHappy}/>{happy&&<><Input label="Happy hour starts" type="time" value={happyStart} onChange={setHappyStart}/><Input label="Happy hour ends" type="time" value={happyEnd} onChange={setHappyEnd}/></>}</div><div style={{display:'flex',gap:18,flexWrap:'wrap'}}><label><input type="checkbox" checked={sold} onChange={e=>setSold(e.target.checked)}/> Sold out</label><label><input type="checkbox" checked={age} onChange={e=>setAge(e.target.checked)}/> Age restricted</label>{age&&<Input label="Minimum age" type="number" value={minimumAge} onChange={setMinimumAge}/>}</div><div style={{marginTop:14}}><Btn disabled={!id} onClick={()=>act(()=>hospitalityOpsApi.menu(id,{preparationStation:station==='NONE'?null:station,mealPeriods:periods.split(',').map(value=>value.trim()).filter(Boolean),sizes:parse(sizes),extras:parse(extras),variants:parse(variants),comboProductIds:combos.split(',').map(value=>value.trim()).filter(Boolean),soldOut:sold,happyHourPrice:happy?Number(happy):null,happyHourStart:happy?happyStart:null,happyHourEnd:happy?happyEnd:null,ageRestricted:age,minimumAge:age?Number(minimumAge):null}))}>Save menu controls</Btn></div><p style={{fontSize:12,color:'var(--b360-text-secondary)'}}>Use “Name:price” for priced options, for example “Single:0, Double:150”. These choices appear in the hospitality sale dialog.</p></Card>
}
 function ReportView({report}:{report:any}){const sections=[['By waiter',report.byWaiter],['By table',report.byTable],['By item',report.byItem],['By category',report.byCategory],['By hour',report.byHour],['Payment method',report.byPaymentMethod],['Channel',report.byChannel],['Shift',report.byShift],['Location',report.byLocation]];return <><div className="responsive-grid responsive-grid-4"><KpiCard title="Food cost" value={`KES ${report.foodCost.toLocaleString()}`} change="Recipe cost" icon={<ChefHat size={18}/>} color="var(--b360-amber)"/><KpiCard title="Beverage cost" value={`KES ${report.beverageCost.toLocaleString()}`} change="Recipe cost" icon={<Package size={18}/>} color="var(--b360-blue)"/><KpiCard title="Wastage" value={`KES ${report.wastageCost.toLocaleString()}`} change="Loss events" icon={<AlertTriangle size={18}/>} color="var(--b360-red)"/><KpiCard title="Gross margin" value={`${report.grossMargin.toFixed(1)}%`} change={`${report.averageTableTurnoverMinutes.toFixed(0)} min turnover`} icon={<ShoppingCart size={18}/>} color="var(--b360-green)"/></div><div className="responsive-grid responsive-grid-2">{sections.map(([title,rows]:any)=><Card key={title} style={{padding:16}}><h3>{title}</h3>{rows.map((r:any)=><div key={r.label} style={{display:'flex',justifyContent:'space-between',padding:'7px 0',borderBottom:'1px solid var(--b360-border)',fontSize:12}}><span>{r.label} · {r.count}</span><b>KES {r.amount.toLocaleString()}</b></div>)}</Card>)}</div></>}
