import React,{useEffect,useMemo,useState} from 'react'
import {AlertTriangle,Calendar,ChefHat,ClipboardCheck,Package,RefreshCw,ShoppingCart,Users} from 'lucide-react'
import {Btn,Card,DataTable,Input,KpiCard,PageHeader,Select,StatusBadge} from '../components/ui'
import {HospitalityOperations,ProductResponse,hospitalityApi,hospitalityOpsApi,productApi} from '../services/api'

type Tab='FLOOR'|'RESERVATIONS'|'MENU'|'STOCK'|'SHIFTS'|'PURCHASING'|'APPROVALS'|'REPORTS'
const today=()=>new Date().toISOString().slice(0,10)
export default function HospitalityOperationsPage(){
 const [tab,setTab]=useState<Tab>('FLOOR'),[data,setData]=useState<HospitalityOperations|null>(null),[tables,setTables]=useState<any[]>([]),[products,setProducts]=useState<ProductResponse[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState('')
 const [reservation,setReservation]=useState({tableId:'',customerName:'',customerPhone:'',guestCount:'2',reservedAt:'',notes:''})
 const [ingredient,setIngredient]=useState({name:'',unit:'ML',quantity:'0',reorderLevel:'0',unitCost:'0'})
 const [supplier,setSupplier]=useState({name:'',phone:'',email:'',address:''})
 const [float,setFloat]=useState('0'),[reportDates,setReportDates]=useState({startDate:today(),endDate:today()}),[report,setReport]=useState<any>(null)
 const load=async()=>{setLoading(true);try{const[o,h,p]=await Promise.all([hospitalityOpsApi.dashboard(),hospitalityApi.dashboard(),productApi.list()]);if(o.success)setData(o.data);if(h.success)setTables(h.data?.tables||[]);if(p.success)setProducts(p.data||[])}catch(e:any){setMessage(e.response?.data?.message||'Could not load hospitality operations')}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const act=async(fn:()=>Promise<any>)=>{setMessage('');try{const r=await fn();setMessage(r.success===false?r.message:'Saved successfully');if(r.success!==false)await load()}catch(e:any){setMessage(e.response?.data?.message||'Request failed')}}
 const openShift=data?.shifts.find(s=>s.status==='OPEN'),low=data?.ingredients.filter(i=>i.isLowStock)||[]
 const tabs:Tab[]=['FLOOR','RESERVATIONS','MENU','STOCK','SHIFTS','PURCHASING','APPROVALS','REPORTS']
 return <div className="fade-in" style={{display:'flex',flexDirection:'column',gap:16}}><PageHeader title="Hospitality Operations" action={<Btn variant="secondary" icon={<RefreshCw size={14}/>} onClick={load}>Refresh</Btn>}/>
 {message&&<div style={{padding:11,borderRadius:8,background:'var(--b360-green-bg)',color:'var(--b360-text)',fontSize:13}}>{message}</div>}
 <div style={{display:'flex',gap:6,overflowX:'auto',paddingBottom:4}}>{tabs.map(value=><button key={value} onClick={()=>setTab(value)} style={{border:'1px solid var(--b360-border)',borderRadius:18,padding:'7px 12px',whiteSpace:'nowrap',background:tab===value?'var(--b360-green)':'white',color:tab===value?'white':'inherit',cursor:'pointer'}}>{value.replace('_',' ')}</button>)}</div>
 {loading?<Card style={{padding:35,textAlign:'center'}}>Loading operations…</Card>:!data?<Card style={{padding:25}}>Operations unavailable.</Card>:<>
 {tab==='FLOOR'&&<><div className="responsive-grid responsive-grid-4"><KpiCard title="Tables" value={String(tables.length)} change={`${tables.filter(t=>t.status==='OCCUPIED').length} occupied`} icon={<Users size={18}/>} color="var(--b360-blue)"/><KpiCard title="Reservations" value={String(data.reservations.filter(r=>r.status==='BOOKED').length)} change="Upcoming" icon={<Calendar size={18}/>} color="var(--b360-amber)"/><KpiCard title="Open shift" value={openShift?'Yes':'No'} change={openShift?'Trading active':'Start a shift'} icon={<ClipboardCheck size={18}/>} color="var(--b360-green)"/><KpiCard title="Low ingredients" value={String(low.length)} change="Need purchasing" icon={<AlertTriangle size={18}/>} color="var(--b360-red)"/></div><Card style={{padding:18}}><h3>Floor plan</h3><div style={{position:'relative',minHeight:420,marginTop:12,background:'#F8FAFC',border:'1px dashed var(--b360-border)',borderRadius:12,overflow:'auto'}}>{tables.filter(t=>!t.mergedIntoTableId).map((table,index)=><button key={table.id} onClick={()=>{const waiter=window.prompt('Waiter user ID (blank keeps current)',table.waiterUserId||'');if(waiter!==null)act(()=>hospitalityOpsApi.table(table.id,{waiterUserId:waiter||table.waiterUserId,positionX:table.positionX||40+(index%5)*150,positionY:table.positionY||40+Math.floor(index/5)*100}))}} style={{position:'absolute',left:table.positionX||40+(index%5)*150,top:table.positionY||40+Math.floor(index/5)*100,width:120,height:70,border:`2px solid ${table.status==='OCCUPIED'?'var(--b360-amber)':'var(--b360-green)'}`,borderRadius:table.shape==='CIRCLE'?'50%':12,background:'white',cursor:'pointer'}}><b>{table.name}</b><small style={{display:'block'}}>{table.capacity} seats · {table.status}</small></button>)}</div><p style={{fontSize:11,color:'var(--b360-text-secondary)'}}>Select a table to assign a waiter. Position and merge data are persisted by the operations API.</p></Card></>}
 {tab==='RESERVATIONS'&&<><Card style={{padding:18}}><h3>New reservation</h3><div className="responsive-grid responsive-grid-3" style={{marginTop:12}}><Select label="Table" value={reservation.tableId} onChange={v=>setReservation({...reservation,tableId:v})} options={[{value:'',label:'Assign later'},...tables.map(t=>({value:t.id,label:t.name}))]}/><Input label="Customer" value={reservation.customerName} onChange={v=>setReservation({...reservation,customerName:v})}/><Input label="Phone" value={reservation.customerPhone} onChange={v=>setReservation({...reservation,customerPhone:v})}/><Input label="Guests" type="number" value={reservation.guestCount} onChange={v=>setReservation({...reservation,guestCount:v})}/><Input label="Date and time" type="datetime-local" value={reservation.reservedAt} onChange={v=>setReservation({...reservation,reservedAt:v})}/><Input label="Notes" value={reservation.notes} onChange={v=>setReservation({...reservation,notes:v})}/></div><Btn onClick={()=>act(()=>hospitalityOpsApi.reservation({...reservation,tableId:reservation.tableId||null,guestCount:Number(reservation.guestCount),reservedAt:new Date(reservation.reservedAt).toISOString()}))}>Book reservation</Btn></Card><DataTable headers={['Time','Customer','Guests','Table','Status','Actions']} rows={data.reservations.map(r=>[new Date(r.reservedAt).toLocaleString('en-KE'),r.customerName,r.guestCount,tables.find(t=>t.id===r.tableId)?.name||'Unassigned',<StatusBadge status={r.status}/>,<div style={{display:'flex',gap:5}}><Btn small onClick={()=>act(()=>hospitalityOpsApi.reservationStatus(r.id,'SEATED'))}>Seat</Btn><Btn small variant="secondary" onClick={()=>act(()=>hospitalityOpsApi.reservationStatus(r.id,'CANCELLED'))}>Cancel</Btn></div>])}/></>}
 {tab==='MENU'&&<MenuProfiles products={products} data={data} act={act}/>} 
 {tab==='STOCK'&&<><Card style={{padding:18}}><h3>Add ingredient</h3><div className="responsive-grid responsive-grid-4" style={{margin:'12px 0'}}><Input label="Name" value={ingredient.name} onChange={v=>setIngredient({...ingredient,name:v})}/><Input label="Unit" value={ingredient.unit} onChange={v=>setIngredient({...ingredient,unit:v})}/><Input label="Opening quantity" type="number" value={ingredient.quantity} onChange={v=>setIngredient({...ingredient,quantity:v})}/><Input label="Reorder level" type="number" value={ingredient.reorderLevel} onChange={v=>setIngredient({...ingredient,reorderLevel:v})}/><Input label="Unit cost" type="number" value={ingredient.unitCost} onChange={v=>setIngredient({...ingredient,unitCost:v})}/></div><Btn onClick={()=>act(()=>hospitalityOpsApi.ingredient({...ingredient,quantity:Number(ingredient.quantity),reorderLevel:Number(ingredient.reorderLevel),unitCost:Number(ingredient.unitCost)}))}>Add ingredient</Btn></Card><DataTable headers={['Ingredient','Unit','On hand','Reorder','Unit cost','Status','Bar controls']} rows={data.ingredients.map(i=>[i.name,i.unit,i.quantity,i.reorderLevel,`KES ${i.unitCost.toLocaleString()}`,<StatusBadge status={i.isLowStock?'LOW':'ACTIVE'}/>,<Btn small variant="secondary" onClick={()=>{const type=window.prompt('Event: OPEN_BOTTLE, SHOT, WASTAGE, BREAKAGE, SPILLAGE, COMPLIMENTARY, STOCK_IN or VARIANCE','WASTAGE');const qty=window.prompt('Quantity','1');if(type&&qty)act(()=>hospitalityOpsApi.barStock({ingredientId:i.id,eventType:type,quantity:Number(qty),unit:i.unit,reason:'Recorded from hospitality operations'}))}}>Record event</Btn>])}/></>}
 {tab==='SHIFTS'&&<><Card style={{padding:18}}>{openShift?<><h3>Close current shift</h3><p>Opened {new Date(openShift.openedAt).toLocaleString('en-KE')} · Float KES {openShift.openingFloat.toLocaleString()}</p><Btn onClick={()=>{const cash=window.prompt('Actual cash counted','0');if(cash!==null)act(()=>hospitalityOpsApi.closeShift(openShift.id,{actualCash:Number(cash),tipsTotal:0,expensesTotal:0,notes:''}))}}>Close and reconcile</Btn></>:<><h3>Start shift</h3><div style={{maxWidth:260,margin:'12px 0'}}><Input label="Opening float (KES)" type="number" value={float} onChange={setFloat}/></div><Btn onClick={()=>act(()=>hospitalityOpsApi.openShift({openingFloat:Number(float),notes:''}))}>Open shift</Btn></>}</Card><DataTable headers={['Opened','Closed','Float','Expected cash','Actual cash','M-Pesa','Card','Variance','Status']} rows={data.shifts.map(s=>[new Date(s.openedAt).toLocaleString('en-KE'),s.closedAt?new Date(s.closedAt).toLocaleString('en-KE'):'—',s.openingFloat,s.expectedCash??'—',s.actualCash??'—',s.mpesaTotal??'—',s.cardTotal??'—',s.variance??'—',<StatusBadge status={s.status}/>])}/></>}
 {tab==='PURCHASING'&&<><Card style={{padding:18}}><h3>Add supplier</h3><div className="responsive-grid responsive-grid-4" style={{margin:'12px 0'}}><Input label="Name" value={supplier.name} onChange={v=>setSupplier({...supplier,name:v})}/><Input label="Phone" value={supplier.phone} onChange={v=>setSupplier({...supplier,phone:v})}/><Input label="Email" value={supplier.email} onChange={v=>setSupplier({...supplier,email:v})}/><Input label="Address" value={supplier.address} onChange={v=>setSupplier({...supplier,address:v})}/></div><Btn onClick={()=>act(()=>hospitalityOpsApi.supplier(supplier))}>Add supplier</Btn></Card><DataTable headers={['PO','Supplier','Total','Ordered','Received','Status','Action']} rows={data.purchaseOrders.map(po=>[po.orderNumber,data.suppliers.find(s=>s.id===po.supplierId)?.name||po.supplierId,`KES ${po.totalCost.toLocaleString()}`,new Date(po.orderedAt).toLocaleDateString(),po.receivedAt?new Date(po.receivedAt).toLocaleDateString():'—',<StatusBadge status={po.status}/>,po.status!=='RECEIVED'?<Btn small onClick={()=>act(()=>hospitalityOpsApi.receivePurchaseOrder(po.id))}>Receive goods</Btn>:'—'])}/><p style={{fontSize:12,color:'var(--b360-text-secondary)'}}>Purchase orders can be created through the shared operations API with supplier, ingredient quantities, and unit costs.</p></>}
 {tab==='APPROVALS'&&<DataTable headers={['Action','Entity','Reason','Requested','Status','Decision']} rows={data.approvals.map(a=>[a.actionType,`${a.entityType} · ${a.entityId.slice(0,8)}`,a.reason,new Date(a.requestedAt).toLocaleString('en-KE'),<StatusBadge status={a.status}/>,a.status==='PENDING'?<div style={{display:'flex',gap:5}}><Btn small onClick={()=>act(()=>hospitalityOpsApi.decideApproval(a.id,true))}>Approve</Btn><Btn small variant="danger" onClick={()=>act(()=>hospitalityOpsApi.decideApproval(a.id,false))}>Reject</Btn></div>:'—'])}/>} 
 {tab==='REPORTS'&&<><Card style={{padding:18}}><div style={{display:'flex',gap:10,alignItems:'end',flexWrap:'wrap'}}><Input label="From" type="date" value={reportDates.startDate} onChange={v=>setReportDates({...reportDates,startDate:v})}/><Input label="To" type="date" value={reportDates.endDate} onChange={v=>setReportDates({...reportDates,endDate:v})}/><Btn onClick={async()=>{const r=await hospitalityOpsApi.report(reportDates.startDate,reportDates.endDate);setReport(r.data)}}>Run report</Btn></div></Card>{report&&<ReportView report={report}/>}</>}
 </>}</div>
}
function MenuProfiles({products,data,act}:{products:ProductResponse[];data:HospitalityOperations;act:(fn:()=>Promise<any>)=>void}){const [id,setId]=useState(''),[station,setStation]=useState('KITCHEN'),[sold,setSold]=useState(false),[age,setAge]=useState(false),[happy,setHappy]=useState('');const profile=data.menuProfiles.find(p=>p.productId===id);useEffect(()=>{if(profile){setStation(profile.preparationStation||'KITCHEN');setSold(profile.soldOut);setAge(profile.ageRestricted);setHappy(profile.happyHourPrice?.toString()||'')}},[id]);return <Card style={{padding:18}}><h3>Menu availability and routing</h3><div className="responsive-grid responsive-grid-3" style={{margin:'12px 0'}}><Select label="Menu item" value={id} onChange={setId} options={[{value:'',label:'Select product'},...products.map(p=>({value:p.id,label:p.name}))]}/><Select label="Preparation station" value={station} onChange={setStation} options={[{value:'KITCHEN',label:'Kitchen'},{value:'BAR',label:'Bar'},{value:'NONE',label:'No preparation ticket'}]}/><Input label="Happy-hour price" type="number" value={happy} onChange={setHappy}/></div><label><input type="checkbox" checked={sold} onChange={e=>setSold(e.target.checked)}/> Sold out</label><label style={{marginLeft:18}}><input type="checkbox" checked={age} onChange={e=>setAge(e.target.checked)}/> Age restricted</label><div style={{marginTop:14}}><Btn disabled={!id} onClick={()=>act(()=>hospitalityOpsApi.menu(id,{preparationStation:station==='NONE'?null:station,mealPeriods:[],sizes:profile?.sizes||[],extras:profile?.extras||[],variants:profile?.variants||[],comboProductIds:profile?.comboProductIds||[],soldOut:sold,happyHourPrice:happy?Number(happy):null,happyHourStart:happy?'16:00':null,happyHourEnd:happy?'19:00':null,ageRestricted:age,minimumAge:age?18:null}))}>Save menu controls</Btn></div><p style={{fontSize:12,color:'var(--b360-text-secondary)'}}>Sizes, extras, variants, combos and meal periods are persisted by the same menu profile endpoint and enforced when sent with an order.</p></Card>}
function ReportView({report}:{report:any}){const sections=[['By waiter',report.byWaiter],['By table',report.byTable],['By item',report.byItem],['By category',report.byCategory],['By hour',report.byHour],['Payment method',report.byPaymentMethod],['Channel',report.byChannel],['Shift',report.byShift]];return <><div className="responsive-grid responsive-grid-4"><KpiCard title="Food cost" value={`KES ${report.foodCost.toLocaleString()}`} change="Recipe cost" icon={<ChefHat size={18}/>} color="var(--b360-amber)"/><KpiCard title="Beverage cost" value={`KES ${report.beverageCost.toLocaleString()}`} change="Recipe cost" icon={<Package size={18}/>} color="var(--b360-blue)"/><KpiCard title="Wastage" value={`KES ${report.wastageCost.toLocaleString()}`} change="Loss events" icon={<AlertTriangle size={18}/>} color="var(--b360-red)"/><KpiCard title="Gross margin" value={`${report.grossMargin.toFixed(1)}%`} change={`${report.averageTableTurnoverMinutes.toFixed(0)} min turnover`} icon={<ShoppingCart size={18}/>} color="var(--b360-green)"/></div><div className="responsive-grid responsive-grid-2">{sections.map(([title,rows]:any)=><Card key={title} style={{padding:16}}><h3>{title}</h3>{rows.map((r:any)=><div key={r.label} style={{display:'flex',justifyContent:'space-between',padding:'7px 0',borderBottom:'1px solid var(--b360-border)',fontSize:12}}><span>{r.label} · {r.count}</span><b>KES {r.amount.toLocaleString()}</b></div>)}</Card>)}</div></>}
