import { unitOptions } from '../utils/unitsOfMeasure'
import { StaffShiftReports } from '../components/hospitality/StaffShiftTally'
import { IngredientPurchaseUnits } from '../components/hospitality/IngredientPurchasing'
import React,{useEffect,useMemo,useState} from 'react'
import {useNavigate} from 'react-router-dom'
import {useAuth} from '../App'
import {AlertTriangle,Calendar,ChefHat,ClipboardCheck,Package,RefreshCw,ShoppingCart,Users} from 'lucide-react'
import {Btn,Card,DataTable,Input,KpiCard,Modal,PageHeader,Select,StatusBadge} from '../components/ui'
import {HospitalityOperations,ProductResponse,UserResponse,hospitalityApi,hospitalityOpsApi,productApi,userApi,accessApi} from '../services/api'

type Tab='FLOOR'|'RESERVATIONS'|'MENU'|'STOCK'|'SHIFTS'|'APPROVALS'|'REPORTS'
const foodCategory=(category:string)=>['food','meal','dish','snack','bakery','breakfast','lunch','dinner','restaurant','kitchen','meat','beef','goat','chicken','fish','seafood','dessert','pastry','ugali','chapati','fries'].some(word=>category.trim().toLowerCase().includes(word))
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Nairobi',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())
export default function HospitalityOperationsPage(){
 const navigate = useNavigate()
 const [permissions,setPermissions]=useState<string[]>([]),[orders,setOrders]=useState<any[]>([])
 const can=(key:string)=>permissions.includes('hospitality.'+key)
 const [tab,setTab]=useState<Tab>(()=>new URLSearchParams(window.location.search).get('tab')==='APPROVALS'?'APPROVALS':new URLSearchParams(window.location.search).get('tab')==='SHIFTS'?'SHIFTS':'FLOOR'),[data,setData]=useState<HospitalityOperations|null>(null),[tables,setTables]=useState<any[]>([]),[products,setProducts]=useState<ProductResponse[]>([]),[users,setUsers]=useState<UserResponse[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState('')
 const [tableControl,setTableControl]=useState<any|null>(null),[waiterId,setWaiterId]=useState(''),[mergeId,setMergeId]=useState('')
 const [barControl,setBarControl]=useState<any|null>(null),[barType,setBarType]=useState('WASTAGE'),[barQuantity,setBarQuantity]=useState('1'),[barReason,setBarReason]=useState('')
 const [shiftClose,setShiftClose]=useState<any|null>(null),[actualCash,setActualCash]=useState('0'),[actualMpesa,setActualMpesa]=useState('0'),[actualCard,setActualCard]=useState('0'),[tips,setTips]=useState('0'),[shiftExpenses,setShiftExpenses]=useState('0'),[shiftNotes,setShiftNotes]=useState('')
 const [reservation,setReservation]=useState({tableId:'',customerName:'',customerPhone:'',guestCount:'2',reservedAt:'',notes:''})
 const [ingredient,setIngredient]=useState({name:'',unit:'ML',quantity:'0',reorderLevel:'0',unitCost:'0'})
 const [float,setFloat]=useState('0'),[reportDates,setReportDates]=useState({startDate:today(),endDate:today()}),[report,setReport]=useState<any>(null),[reportLoading,setReportLoading]=useState(false)
 const load=async(silent=false)=>{if(!silent)setLoading(true);try{const[o,h,p,u,a]=await Promise.all([hospitalityOpsApi.dashboard(),hospitalityApi.dashboard(),productApi.list(),hospitalityOpsApi.staff().catch(()=>null),accessApi.me()]);if(a.success)setPermissions(a.data?.permissions||[]);if(o.success)setData(o.data);if(h.success)setOrders(h.data?.openTabs||[]);if(h.success)setTables(h.data?.tables||[]);if(p.success)setProducts(p.data||[]);if(u?.success)setUsers((u.data||[]).filter((user:any)=>user.isActive!==false))}catch(e:any){setMessage(e.response?.data?.message||'Could not load hospitality operations')}finally{if(!silent)setLoading(false)}}
 useEffect(()=>{if(new URLSearchParams(window.location.search).get('tab')==='PURCHASING'){navigate('/purchases?type=ingredients',{replace:true});return}load();const timer=window.setInterval(()=>load(true),5000);return()=>window.clearInterval(timer)},[])
 const act=async(fn:()=>Promise<any>)=>{setMessage('');try{const r=await fn();setMessage(r.success===false?r.message:'Saved successfully');if(r.success!==false)await load()}catch(e:any){setMessage(e.response?.data?.message||'Request failed')}}
 const bookReservation=()=>{const customerName=reservation.customerName.trim();const guestCount=Number(reservation.guestCount);const reservedAt=reservation.reservedAt?new Date(reservation.reservedAt):null;if(!customerName){setMessage('Customer name is required.');return}if(!reservedAt||Number.isNaN(reservedAt.getTime())){setMessage('Choose a valid reservation date and time.');return}if(!Number.isInteger(guestCount)||guestCount<1||guestCount>100){setMessage('Guests must be a whole number between 1 and 100.');return}act(()=>hospitalityOpsApi.reservation({...reservation,customerName,tableId:reservation.tableId||null,guestCount,reservedAt:reservedAt.toISOString()}))}
 const runReport=async()=>{if(!reportDates.startDate||!reportDates.endDate||reportDates.startDate>reportDates.endDate){setMessage('Choose a valid report date range.');return}setReportLoading(true);setMessage('');try{const r=await hospitalityOpsApi.report(reportDates.startDate,reportDates.endDate);if(r.success===false)throw new Error(r.message||'Could not load report');setReport(r.data)}catch(e:any){setMessage(e.response?.data?.message||e.message||'Could not load report')}finally{setReportLoading(false)}}
 const openShift=data?.shifts.find(s=>s.status==='OPEN'),low=data?.ingredients.filter(i=>i.isLowStock)||[]
 const allTabs:Tab[]=['FLOOR','RESERVATIONS','MENU','STOCK','SHIFTS','APPROVALS','REPORTS']
 const tabs=allTabs.filter(t=>t==='APPROVALS'||can(t.toLowerCase()))
 useEffect(()=>{if(permissions.length&&tabs.length&&!tabs.includes(tab))setTab(tabs[0])},[permissions.join(',')])
 return <div className="fade-in" style={{display:'flex',flexDirection:'column',gap:16}}><PageHeader title="Hospitality Operations" action={<div style={{display:'flex',gap:8}}>{can('purchasing')&&<Btn variant="secondary" icon={<ShoppingCart size={14}/>} onClick={()=>navigate('/purchases?type=ingredients')}>Purchases</Btn>}<Btn variant="secondary" icon={<RefreshCw size={14}/>} onClick={load}>Refresh</Btn></div>}/>
 {message&&<div style={{padding:11,borderRadius:8,background:'var(--b360-green-bg)',color:'var(--b360-text)',fontSize:13}}>{message}</div>}
 <div style={{display:'flex',gap:6,overflowX:'auto',paddingBottom:4}}>{tabs.map(value=><button key={value} onClick={()=>setTab(value)} style={{border:'1px solid var(--b360-border)',borderRadius:18,padding:'7px 12px',whiteSpace:'nowrap',background:tab===value?'var(--b360-green)':'white',color:tab===value?'white':'inherit',cursor:'pointer'}}>{value.replace('_',' ')}</button>)}</div>
 {loading?<Card style={{padding:35,textAlign:'center'}}>Loading operations…</Card>:!data?<Card style={{padding:25}}>Operations unavailable.</Card>:<>
 {tab==='FLOOR'&&<><div className="responsive-grid responsive-grid-4"><KpiCard title="Tables" value={String(tables.length)} change={`${tables.filter(t=>t.status==='OCCUPIED').length} occupied`} icon={<Users size={18}/>} color="var(--b360-blue)"/><KpiCard title="Reservations" value={String(data.reservations.filter(r=>r.status==='BOOKED').length)} change="Upcoming" icon={<Calendar size={18}/>} color="var(--b360-amber)"/><KpiCard title="Open shift" value={openShift?'Yes':'No'} change={openShift?'Trading active':'Start a shift'} icon={<ClipboardCheck size={18}/>} color="var(--b360-green)"/><KpiCard title="Low ingredients" value={String(low.length)} change="Need purchasing" icon={<AlertTriangle size={18}/>} color="var(--b360-red)"/></div><Card style={{padding:18}}><h3>Floor plan</h3><div style={{position:'relative',minHeight:420,marginTop:12,background:'#F8FAFC',border:'1px dashed var(--b360-border)',borderRadius:12,overflow:'auto'}}>{tables.map((table,index)=><button key={table.id} onClick={()=>{setTableControl(table);setWaiterId(table.waiterUserId||'');setMergeId(table.mergedIntoTableId||'')}} style={{position:'absolute',left:table.positionX??40+(index%5)*150,top:table.positionY??40+Math.floor(index/5)*100,width:120,height:70,border:`2px solid ${table.status==='OCCUPIED'?'var(--b360-amber)':'var(--b360-green)'}`,borderRadius:table.shape==='CIRCLE'?'50%':12,background:'white',cursor:'pointer'}}><b>{table.name}</b><small style={{display:'block'}}>{table.capacity} seats · {table.mergedIntoTableId?'MERGED':table.status}</small></button>)}</div><p style={{fontSize:11,color:'var(--b360-text-secondary)'}}>Select a table to assign a waiter, merge it, or adjust its layout.</p></Card></>}
 {tab==='RESERVATIONS'&&<><Card style={{padding:18}}><h3>New reservation</h3><div className="responsive-grid responsive-grid-3" style={{marginTop:12}}><Select label="Table" value={reservation.tableId} onChange={v=>setReservation({...reservation,tableId:v})} options={[{value:'',label:'Assign later'},...tables.map(t=>({value:t.id,label:t.name}))]}/><Input label="Customer" value={reservation.customerName} onChange={v=>setReservation({...reservation,customerName:v})}/><Input label="Phone" value={reservation.customerPhone} onChange={v=>setReservation({...reservation,customerPhone:v})}/><Input label="Guests" type="number" value={reservation.guestCount} onChange={v=>setReservation({...reservation,guestCount:v})}/><Input label="Date and time" type="datetime-local" value={reservation.reservedAt} onChange={v=>setReservation({...reservation,reservedAt:v})}/><Input label="Notes" value={reservation.notes} onChange={v=>setReservation({...reservation,notes:v})}/></div><Btn onClick={bookReservation}>Book reservation</Btn></Card><DataTable headers={['Time','Customer','Guests','Table','Status','Actions']} rows={data.reservations.map(r=>[new Date(r.reservedAt).toLocaleString('en-KE'),r.customerName,r.guestCount,tables.find(t=>t.id===r.tableId)?.name||'Unassigned',<StatusBadge status={r.status}/>,r.status==='BOOKED'?<div style={{display:'flex',gap:5}}><Btn small onClick={()=>act(()=>hospitalityOpsApi.reservationStatus(r.id,'SEATED'))}>Seat</Btn><Btn small variant="secondary" onClick={()=>act(()=>hospitalityOpsApi.reservationStatus(r.id,'CANCELLED'))}>Cancel</Btn><Btn small variant="secondary" onClick={()=>act(()=>hospitalityOpsApi.reservationStatus(r.id,'NO_SHOW'))}>No show</Btn></div>:r.status==='SEATED'?<Btn small onClick={()=>act(()=>hospitalityOpsApi.reservationStatus(r.id,'COMPLETED'))}>Complete</Btn>:'—'])}/></>}
 {tab==='MENU'&&<><MenuProfiles products={products} data={data} act={act}/><Recipes products={products} data={data} act={act}/></>}
 {tab==='STOCK'&&<><IngredientPurchaseUnits data={data} act={act}/><Card style={{padding:18}}><h3>Add ingredient</h3><div className="responsive-grid responsive-grid-4" style={{margin:'12px 0'}}><Input label="Name" value={ingredient.name} onChange={v=>setIngredient({...ingredient,name:v})}/><Select label="Unit of measure" value={ingredient.unit} onChange={v=>setIngredient({...ingredient,unit:v})} options={unitOptions(ingredient.unit)}/><Input label="Opening quantity" type="number" value={ingredient.quantity} onChange={v=>setIngredient({...ingredient,quantity:v})}/><Input label="Reorder level" type="number" value={ingredient.reorderLevel} onChange={v=>setIngredient({...ingredient,reorderLevel:v})}/><Input label="Unit cost" type="number" value={ingredient.unitCost} onChange={v=>setIngredient({...ingredient,unitCost:v})}/></div><Btn onClick={()=>act(()=>hospitalityOpsApi.ingredient({...ingredient,quantity:Number(ingredient.quantity),reorderLevel:Number(ingredient.reorderLevel),unitCost:Number(ingredient.unitCost)}))}>Add ingredient</Btn></Card><DataTable headers={['Ingredient','Unit','On hand','Reorder','Unit cost','Status','Bar controls']} rows={data.ingredients.map(i=>[i.name,i.unit,i.quantity,i.reorderLevel,`KES ${i.unitCost.toLocaleString()}`,<StatusBadge status={i.isLowStock?'LOW':'ACTIVE'}/>,<Btn small variant="secondary" onClick={()=>{setBarControl(i);setBarType('WASTAGE');setBarQuantity('1');setBarReason('')}}>Record event</Btn>])}/></>}
 {tab==='SHIFTS'&&<><StaffShiftReports/><Card style={{padding:18}}>{openShift?<><h3>End of day · close and reconcile</h3><p>Supplier cash paid from drawer: KES {(openShift.supplierCashPayments||0).toLocaleString()} · deducted automatically at closing.</p><p>Opened {new Date(openShift.openedAt).toLocaleString('en-KE')} · Opening float KES {openShift.openingFloat.toLocaleString()}</p><p style={{fontSize:12,color:'var(--b360-text-secondary)'}}>All open tabs and successful payments must be settled or reconciled before the day can close.</p><Btn onClick={()=>{setShiftClose(openShift);setActualCash('0');setActualMpesa('0');setActualCard('0');setTips('0');setShiftExpenses('0');setShiftNotes('')}}>Close and reconcile day</Btn></>:<><h3>Start of day · open shift</h3><p style={{fontSize:12,color:'var(--b360-text-secondary)'}}>Users must open a shift before taking hospitality orders or settling payments.</p><div style={{maxWidth:260,margin:'12px 0'}}><Input label="Opening float (KES)" type="number" value={float} onChange={setFloat}/></div><Btn onClick={()=>act(()=>hospitalityOpsApi.openShift({openingFloat:Number(float),notes:''}))}>Open shift</Btn></>}</Card><DataTable headers={['Opened','Closed','Float','Expected cash','Counted cash','Expected M-Pesa','Counted M-Pesa','Expected card','Counted card','Variance','Status']} rows={data.shifts.map(s=>[new Date(s.openedAt).toLocaleString('en-KE'),s.closedAt?new Date(s.closedAt).toLocaleString('en-KE'):'—',s.openingFloat,s.expectedCash??'—',s.actualCash??'—',s.mpesaTotal??'—',s.actualMpesa??'—',s.cardTotal??'—',s.actualCard??'—',s.totalVariance??s.variance??'—',<StatusBadge status={s.status}/>])}/></>}
 {tab==='APPROVALS'&&<Approvals data={data} orders={orders} canDecide={can('approvals')} act={act}/>}
 {tab==='REPORTS'&&<><Card style={{padding:18}}><div style={{display:'flex',gap:10,alignItems:'end',flexWrap:'wrap'}}><Input label="From" type="date" value={reportDates.startDate} onChange={v=>setReportDates({...reportDates,startDate:v})}/><Input label="To" type="date" value={reportDates.endDate} onChange={v=>setReportDates({...reportDates,endDate:v})}/><Btn onClick={runReport} disabled={reportLoading}>{reportLoading?'Loading…':'Run report'}</Btn></div></Card>{report&&<ReportView report={report}/>}</>}
 </>}
 {tableControl&&<Modal title={`Table controls · ${tableControl.name}`} onClose={()=>setTableControl(null)} footer={<><Btn variant="secondary" onClick={()=>setTableControl(null)}>Cancel</Btn><Btn onClick={()=>act(async()=>{const result=await hospitalityOpsApi.table(tableControl.id,{waiterUserId:waiterId||null,mergeIntoTableId:mergeId||null,positionX:tableControl.positionX??40,positionY:tableControl.positionY??40,shape:tableControl.shape||'RECTANGLE'});setTableControl(null);return result})}>Save controls</Btn></>}><div style={{display:'grid',gap:12}}><Select label="Assigned waiter" value={waiterId} onChange={setWaiterId} options={[{value:'',label:'Unassigned'},...users.map(user=>({value:user.id,label:`${user.name} · ${user.role}`}))]}/><Select label="Merge into table" value={mergeId} onChange={setMergeId} options={[{value:'',label:'Do not merge'},...tables.filter(table=>table.id!==tableControl.id&&!table.mergedIntoTableId).map(table=>({value:table.id,label:table.name}))]}/><Select label="Shape" value={tableControl.shape||'RECTANGLE'} onChange={value=>setTableControl({...tableControl,shape:value})} options={[{value:'RECTANGLE',label:'Rectangle'},{value:'CIRCLE',label:'Circle'}]}/><div className="responsive-grid responsive-grid-2"><Input label="Floor X position" type="number" value={String(tableControl.positionX??0)} onChange={value=>setTableControl({...tableControl,positionX:Number(value)})}/><Input label="Floor Y position" type="number" value={String(tableControl.positionY??0)} onChange={value=>setTableControl({...tableControl,positionY:Number(value)})}/></div></div></Modal>}
 {barControl&&<Modal title={`Stock event · ${barControl.name}`} onClose={()=>setBarControl(null)} footer={<><Btn variant="secondary" onClick={()=>setBarControl(null)}>Cancel</Btn><Btn onClick={()=>act(async()=>{const result=await hospitalityOpsApi.barStock({ingredientId:barControl.id,eventType:barType,quantity:Number(barQuantity),unit:barControl.unit,reason:barReason});setBarControl(null);return result})}>Record event</Btn></>}><div style={{display:'grid',gap:12}}><Select label="Event" value={barType} onChange={setBarType} options={['OPEN_BOTTLE','SHOT','WASTAGE','BREAKAGE','SPILLAGE','COMPLIMENTARY','STOCK_IN','VARIANCE'].map(value=>({value,label:value.replace(/_/g,' ')}))}/><Input label={`Quantity (${barControl.unit})`} type="number" value={barQuantity} onChange={setBarQuantity}/><Input label="Reason / reference" value={barReason} onChange={setBarReason}/></div></Modal>}
 {shiftClose&&<Modal title="End of day · reconcile payments" onClose={()=>setShiftClose(null)} footer={<><Btn variant="secondary" onClick={()=>setShiftClose(null)}>Cancel</Btn><Btn onClick={()=>act(async()=>{const result=await hospitalityOpsApi.closeShift(shiftClose.id,{actualCash:Number(actualCash),actualMpesa:Number(actualMpesa),actualCard:Number(actualCard),tipsTotal:Number(tips),expensesTotal:Number(shiftExpenses),notes:shiftNotes});setShiftClose(null);return result})}>Close day</Btn></>}><div style={{display:'grid',gap:12}}><p>Supplier payments deducted from drawer: KES {(shiftClose.supplierCashPayments||0).toLocaleString()}. Do not include these again under other cash expenses.</p><Input label="Cash counted (KES)" type="number" value={actualCash} onChange={setActualCash}/><Input label="M-Pesa received (KES)" type="number" value={actualMpesa} onChange={setActualMpesa}/><Input label="Card receipts (KES)" type="number" value={actualCard} onChange={setActualCard}/><Input label="Tips (KES)" type="number" value={tips} onChange={setTips}/><Input label="Other cash expenses (KES)" type="number" value={shiftExpenses} onChange={setShiftExpenses}/><Input label="Reconciliation notes" value={shiftNotes} onChange={setShiftNotes}/><p style={{fontSize:12,color:'var(--b360-text-secondary)',margin:0}}>Ingredient payments marked as paid from the cash drawer are deducted automatically. Enter other cash expenses only. The server compares your counts with the payment ledger and records any variance. Unreconciled successful payments and open tabs block close.</p></div></Modal>}
 </div>
}
function MenuProfiles({products,data,act}:{products:ProductResponse[];data:HospitalityOperations;act:(fn:()=>Promise<any>)=>void}){
 const [id,setId]=useState(''),[station,setStation]=useState('KITCHEN'),[sold,setSold]=useState(false),[age,setAge]=useState(false),[minimumAge,setMinimumAge]=useState('18'),[happy,setHappy]=useState(''),[happyStart,setHappyStart]=useState('16:00'),[happyEnd,setHappyEnd]=useState('19:00'),[periods,setPeriods]=useState(''),[sizes,setSizes]=useState(''),[extras,setExtras]=useState(''),[variants,setVariants]=useState(''),[combos,setCombos]=useState('')
 const profile=data.menuProfiles.find(p=>p.productId===id)
 const format=(items:Array<{name:string;priceDelta:number}>)=>items.map(item=>`${item.name}:${item.priceDelta}`).join(', ')
 const parse=(value:string)=>value.split(',').map(item=>item.trim()).filter(Boolean).map(item=>{const[name,price='0']=item.split(':');return{name:name.trim(),priceDelta:Number(price)||0}})
 useEffect(()=>{if(profile){setStation(profile.preparationStation||'NONE');setSold(profile.soldOut);setAge(profile.ageRestricted);setMinimumAge(String(profile.minimumAge||18));setHappy(profile.happyHourPrice?.toString()||'');setHappyStart(profile.happyHourStart||'16:00');setHappyEnd(profile.happyHourEnd||'19:00');setPeriods(profile.mealPeriods.join(', '));setSizes(format(profile.sizes));setExtras(format(profile.extras));setVariants(format(profile.variants));setCombos(profile.comboProductIds.join(', '))}else{setStation(foodCategory(products.find(p=>p.id===id)?.category||'')?'KITCHEN':'NONE');setSold(false);setAge(false);setMinimumAge('18');setHappy('');setHappyStart('16:00');setHappyEnd('19:00');setPeriods('');setSizes('');setExtras('');setVariants('');setCombos('')}},[id])
 return <Card style={{padding:18}}><h3>Menu availability and routing</h3><div className="responsive-grid responsive-grid-3" style={{margin:'12px 0'}}><Select label="Menu item" value={id} onChange={setId} options={[{value:'',label:'Select product'},...products.map(p=>({value:p.id,label:p.name}))]}/><Select label="Preparation station" value={station} onChange={setStation} options={[...(foodCategory(products.find(p=>p.id===id)?.category||'')?[{value:'KITCHEN',label:'Kitchen'}]:[]),{value:'NONE',label:'No preparation ticket'}]}/><Input label="Meal periods (comma separated)" value={periods} onChange={setPeriods}/><Input label="Sizes (Name:price, …)" value={sizes} onChange={setSizes}/><Input label="Extras (Name:price, …)" value={extras} onChange={setExtras}/><Input label="Variants (Name:price, …)" value={variants} onChange={setVariants}/><Input label="Combo product IDs" value={combos} onChange={setCombos}/><Input label="Happy-hour price" type="number" value={happy} onChange={setHappy}/>{happy&&<><Input label="Happy hour starts" type="time" value={happyStart} onChange={setHappyStart}/><Input label="Happy hour ends" type="time" value={happyEnd} onChange={setHappyEnd}/></>}</div><div style={{display:'flex',gap:18,flexWrap:'wrap'}}><label><input type="checkbox" checked={sold} onChange={e=>setSold(e.target.checked)}/> Sold out</label><label><input type="checkbox" checked={age} onChange={e=>setAge(e.target.checked)}/> Age restricted</label>{age&&<Input label="Minimum age" type="number" value={minimumAge} onChange={setMinimumAge}/>}</div><div style={{marginTop:14}}><Btn disabled={!id} onClick={()=>act(()=>hospitalityOpsApi.menu(id,{preparationStation:station==='NONE'?null:station,mealPeriods:periods.split(',').map(value=>value.trim()).filter(Boolean),sizes:parse(sizes),extras:parse(extras),variants:parse(variants),comboProductIds:combos.split(',').map(value=>value.trim()).filter(Boolean),soldOut:sold,happyHourPrice:happy?Number(happy):null,happyHourStart:happy?happyStart:null,happyHourEnd:happy?happyEnd:null,ageRestricted:age,minimumAge:age?Number(minimumAge):null}))}>Save menu controls</Btn></div><p style={{fontSize:12,color:'var(--b360-text-secondary)'}}>Use “Name:price” for priced options, for example “Single:0, Double:150”. These choices appear in the hospitality sale dialog. Only food categories can create kitchen tickets; drinks and other items need no preparation ticket.</p></Card>
}
 function ReportView({report}:{report:any}){const sections=[['By waiter',report.byWaiter],['By table',report.byTable],['By item',report.byItem],['By category',report.byCategory],['By hour',report.byHour],['Payment method',report.byPaymentMethod],['Channel',report.byChannel],['Shift',report.byShift],['Location',report.byLocation]];return <><div className="responsive-grid responsive-grid-4"><KpiCard title="Food cost" value={`KES ${report.foodCost.toLocaleString()}`} change="Recipe cost" icon={<ChefHat size={18}/>} color="var(--b360-amber)"/><KpiCard title="Beverage cost" value={`KES ${report.beverageCost.toLocaleString()}`} change="Recipe cost" icon={<Package size={18}/>} color="var(--b360-blue)"/><KpiCard title="Wastage" value={`KES ${report.wastageCost.toLocaleString()}`} change="Loss events" icon={<AlertTriangle size={18}/>} color="var(--b360-red)"/><KpiCard title="Gross margin" value={`${report.grossMargin.toFixed(1)}%`} change={`${report.averageTableTurnoverMinutes.toFixed(0)} min turnover`} icon={<ShoppingCart size={18}/>} color="var(--b360-green)"/></div><div className="responsive-grid responsive-grid-2">{sections.map(([title,rows]:any)=><Card key={title} style={{padding:16}}><h3>{title}</h3>{rows.map((r:any)=><div key={r.label} style={{display:'flex',justifyContent:'space-between',padding:'7px 0',borderBottom:'1px solid var(--b360-border)',fontSize:12}}><span>{r.label} · {r.count}</span><b>KES {r.amount.toLocaleString()}</b></div>)}</Card>)}</div></>}
function Recipes({products,data,act}:{products:ProductResponse[];data:HospitalityOperations;act:(fn:()=>Promise<any>)=>void}){
 const [id,setId]=useState(''),[lines,setLines]=useState<Array<{ingredientId:string;quantity:number}>>([]),[error,setError]=useState('')
 useEffect(()=>{let active=true;setLines([]);setError('');if(id)hospitalityOpsApi.getRecipe(id).then(r=>{if(active)setLines(r.data||[])}).catch(()=>{if(active)setError('Could not load this recipe. Select the product again to retry.')});return()=>{active=false}},[id])
 return <Card style={{padding:18}}><h3>Ingredient recipe</h3>{error&&<p role="alert">{error}</p>}<Select label="Recipe product" value={id} onChange={setId} options={[{value:'',label:'Select product'},...products.map(p=>({value:p.id,label:p.name}))]}/>{lines.map((line,index)=><div key={index} style={{display:'flex',gap:8,marginTop:10}}><Select label="Ingredient" value={line.ingredientId} onChange={ingredientId=>setLines(lines.map((l,i)=>i===index?{...l,ingredientId}:l))} options={[{value:'',label:'Select ingredient'},...data.ingredients.map(i=>({value:i.id,label:`${i.name} (${i.unit})`}))]}/><Input label="Quantity per item" type="number" value={String(line.quantity)} onChange={v=>setLines(lines.map((l,i)=>i===index?{...l,quantity:Number(v)}:l))}/><Btn variant="danger" onClick={()=>setLines(lines.filter((_,i)=>i!==index))}>Remove</Btn></div>)}<Btn disabled={!id} onClick={()=>setLines([...lines,{ingredientId:'',quantity:1}])}>Add recipe ingredient</Btn><Btn disabled={!id||!!error||lines.some(l=>!l.ingredientId||l.quantity<=0)} onClick={()=>act(()=>hospitalityOpsApi.recipe(id,lines))}>Save recipe</Btn><p>Quantities use the ingredient stock unit. Saving a recipe switches this product to ingredient-based stock; no separate portion stock is needed. Create separate products for single/double tots or portion sizes. An empty recipe returns to product stock.</p></Card>
}
function Approvals({data,orders,canDecide,act}:{data:HospitalityOperations;orders:any[];canDecide:boolean;act:(fn:()=>Promise<any>)=>void}){
 const {user}=useAuth()
 const [action,setAction]=useState('DISCOUNT_ORDER'),[entityId,setEntityId]=useState(''),[reason,setReason]=useState(''),[amount,setAmount]=useState(''),[quantity,setQuantity]=useState(''),[eventType,setEventType]=useState('WASTAGE')
 const isStock=action==='STOCK_EVENT',isPurchase=action==='RECEIVE_PURCHASE_ORDER'
 const targets=isStock?data.ingredients.map(i=>({value:i.id,label:i.name})):isPurchase?data.purchaseOrders.filter(p=>p.status==='ORDERED').map(p=>({value:p.id,label:p.orderNumber})):orders.filter(o=>o.tabStatus==='OPEN'&&o.paymentStatus==='PENDING').map(o=>({value:o.id,label:`${o.orderNumber} · KES ${o.subtotal}`}))
 return <><Card style={{padding:18}}><h3>Request approval</h3><Select label="Approval action" value={action} onChange={v=>{setAction(v);setEntityId('')}} options={['DISCOUNT_ORDER','COMPLIMENTARY_ORDER','CANCEL_ORDER','STOCK_EVENT','RECEIVE_PURCHASE_ORDER'].map(value=>({value,label:value.replace(/_/g,' ')}))}/><Select label="Approval target" value={entityId} onChange={setEntityId} options={[{value:'',label:'Select target'},...targets]}/>{action==='DISCOUNT_ORDER'&&<Input label="Discount (KES before tax)" type="number" value={amount} onChange={setAmount}/>} {isStock&&<><Select label="Approved stock event" value={eventType} onChange={setEventType} options={['STOCK_IN','WASTAGE','BREAKAGE','SPILLAGE','COMPLIMENTARY','VARIANCE'].map(value=>({value,label:value}))}/><Input label="Approved stock quantity" type="number" value={quantity} onChange={setQuantity}/></>}<Input label="Approval reason" value={reason} onChange={setReason}/><Btn disabled={!entityId||!reason.trim()||(action==='DISCOUNT_ORDER'&&!(Number(amount)>0))||(isStock&&!(Number(quantity)>0))} onClick={()=>act(()=>hospitalityOpsApi.approval({actionType:action,entityType:isStock?'INGREDIENT':isPurchase?'PURCHASE_ORDER':'ORDER',entityId,reason,amount:action==='DISCOUNT_ORDER'?Number(amount):null,quantity:isStock?Number(quantity):null,eventType:isStock?eventType:null}))}>Request approval</Btn><p>Approval applies the action immediately. Another authorized user must decide your request.</p></Card><DataTable headers={['Action','Target','Details','Reason','Status','Decision']} rows={data.approvals.map(a=>[a.actionType,a.entityId,a.amount!=null?`KES ${a.amount}`:a.quantity!=null?`${a.eventType} · ${a.quantity}`:'—',a.reason,<StatusBadge status={a.status}/>,a.status==='PENDING'&&canDecide&&a.requestedBy!==user?.id?<div><Btn small onClick={()=>act(()=>hospitalityOpsApi.decideApproval(a.id,true))}>Approve & apply</Btn><Btn small variant="danger" onClick={()=>act(()=>hospitalityOpsApi.decideApproval(a.id,false))}>Reject</Btn></div>:'—'])}/></>
}
