import React, { useEffect, useRef, useState } from 'react'
import { Bell, Maximize2, RefreshCw } from 'lucide-react'
import { Btn, Card, PageHeader, StatusBadge } from '../components/ui'
import { HospitalityDashboard, KitchenTicket, hospitalityApi } from '../services/api'

export default function KitchenDisplayPage(){
  const [data,setData]=useState<HospitalityDashboard|null>(null),[station,setStation]=useState('ALL'),[error,setError]=useState(''),[alerts,setAlerts]=useState(false),[loading,setLoading]=useState(false)
  const known=useRef(new Set<string>())
  const load=async(silent=false)=>{if(!silent)setLoading(true);try{const result=await hospitalityApi.dashboard();if(!result.success||!result.data)throw new Error(result.message||'Could not load tickets.');const active=result.data.tickets.filter(ticket=>!['SERVED','CANCELLED'].includes(ticket.status));if(alerts&&active.some(ticket=>!known.current.has(ticket.id))&&known.current.size){const audio=new AudioContext();const oscillator=audio.createOscillator();oscillator.connect(audio.destination);oscillator.start();oscillator.stop(audio.currentTime+.18)}known.current=new Set(active.map(ticket=>ticket.id));setData(result.data);setError('')}catch(e:any){setError(e.response?.data?.message||e.message||'Could not load tickets.')}finally{setLoading(false)}}
  useEffect(()=>{load();const timer=window.setInterval(()=>load(true),10000);return()=>window.clearInterval(timer)},[alerts])
  const update=async(ticket:KitchenTicket,status:string)=>{if(status==='CANCELLED'&&!window.confirm(`Cancel ${ticket.orderNumber}? This cannot be undone.`))return;try{const result=await hospitalityApi.updateTicket(ticket.id,status);if(!result.success)throw new Error(result.message);await load(true)}catch(e:any){setError(e.response?.data?.message||e.message||'Could not update ticket.')}}
  const tickets=(data?.tickets||[]).filter(ticket=>!['SERVED','CANCELLED'].includes(ticket.status)&&(station==='ALL'||ticket.station===station)).sort((a,b)=>new Date(a.createdAt).getTime()-new Date(b.createdAt).getTime())
  const age=(value:string)=>Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/60000))
  return <div className="fade-in" style={{display:'grid',gap:16}}><PageHeader title="Kitchen & Bar Display" action={<div style={{display:'flex',gap:8,flexWrap:'wrap'}}><Btn variant="secondary" icon={<Bell size={14}/>} onClick={()=>setAlerts(value=>!value)}>{alerts?'Alerts on':'Enable alerts'}</Btn><Btn variant="secondary" icon={<Maximize2 size={14}/>} onClick={()=>document.documentElement.requestFullscreen?.()}>Full screen</Btn><Btn variant="secondary" icon={<RefreshCw size={14}/>} disabled={loading} onClick={()=>load()}>Refresh</Btn></div>}/>
    {error&&<div role="alert" style={{padding:10,background:'var(--b360-red-bg)',color:'var(--b360-red)',borderRadius:8}}>{error}</div>}
    <div style={{display:'flex',gap:8}}>{['ALL','KITCHEN','BAR'].map(value=><Btn key={value} variant={station===value?'primary':'secondary'} onClick={()=>setStation(value)}>{value==='ALL'?'All stations':value==='KITCHEN'?'Kitchen':'Bar'}</Btn>)}</div>
    {!tickets.length?<Card style={{padding:35,textAlign:'center',color:'var(--b360-text-secondary)'}}>No active tickets for this station.</Card>:<div className="responsive-grid responsive-grid-3">{tickets.map(ticket=>{const minutes=age(ticket.createdAt);return <Card key={ticket.id} style={{padding:18,borderTop:`5px solid ${ticket.status==='READY'?'var(--b360-green)':minutes>=20?'var(--b360-red)':'var(--b360-amber)'}`}}><div style={{display:'flex',justifyContent:'space-between'}}><div><b style={{fontSize:19}}>{ticket.tableName||'Takeaway'}</b><div style={{fontFamily:'monospace',fontSize:12}}>{ticket.orderNumber}</div></div><div style={{textAlign:'right'}}><StatusBadge status={ticket.status}/><div style={{fontWeight:800,color:minutes>=20?'var(--b360-red)':'inherit',marginTop:4}}>{minutes} min</div></div></div><h3 style={{fontSize:12,textTransform:'uppercase',margin:'14px 0 8px'}}>{ticket.station}</h3>{ticket.items.map(item=><div key={item.id} style={{padding:'7px 0',borderBottom:'1px solid var(--b360-border)',fontSize:16}}><b>{item.quantity}×</b> {item.productName}{item.modifiers?.map(option=><small key={option.name} style={{display:'block',paddingLeft:24}}>{option.name}</small>)}{item.itemNote&&<small style={{display:'block',paddingLeft:24,color:'var(--b360-amber)'}}>{item.itemNote}</small>}</div>)}{ticket.notes&&<div style={{padding:9,marginTop:10,background:'var(--b360-amber-bg)',borderRadius:7}}>{ticket.notes}</div>}<div style={{display:'flex',gap:7,marginTop:14,flexWrap:'wrap'}}>{ticket.status==='NEW'&&<Btn onClick={()=>update(ticket,'PREPARING')}>Start</Btn>}{ticket.status==='PREPARING'&&<Btn onClick={()=>update(ticket,'READY')}>Ready</Btn>}{ticket.status==='READY'&&<Btn onClick={()=>update(ticket,'SERVED')}>Served</Btn>}{ticket.status!=='DELAYED'&&<Btn variant="secondary" onClick={()=>update(ticket,'DELAYED')}>Delay</Btn>}<Btn variant="danger" onClick={()=>update(ticket,'CANCELLED')}>Cancel</Btn></div></Card>})}</div>}
  </div>
}
