package com.app.biashara.models

import kotlinx.serialization.Serializable

@Serializable data class ReservationRequest(val tableId:String?=null,val customerName:String,val customerPhone:String="",val guestCount:Int,val reservedAt:String,val durationMinutes:Int=90,val notes:String="")
@Serializable data class ReservationResponse(val id:String,val tableId:String?,val customerName:String,val customerPhone:String,val guestCount:Int,val reservedAt:String,val durationMinutes:Int,val status:String,val notes:String)
@Serializable data class TableOperationsRequest(val waiterUserId:String?=null,val mergeIntoTableId:String?=null,val positionX:Int?=null,val positionY:Int?=null,val shape:String?=null)
@Serializable data class MenuOption(val name:String,val priceDelta:Double=0.0)
@Serializable data class MenuProfileRequest(val preparationStation:String?=null,val mealPeriods:List<String> = emptyList(),val sizes:List<MenuOption> = emptyList(),val extras:List<MenuOption> = emptyList(),val variants:List<MenuOption> = emptyList(),val comboProductIds:List<String> = emptyList(),val soldOut:Boolean=false,val happyHourPrice:Double?=null,val happyHourStart:String?=null,val happyHourEnd:String?=null,val ageRestricted:Boolean=false,val minimumAge:Int?=null)
@Serializable data class MenuProfileResponse(val productId:String,val preparationStation:String?,val mealPeriods:List<String>,val sizes:List<MenuOption>,val extras:List<MenuOption>,val variants:List<MenuOption>,val comboProductIds:List<String>,val soldOut:Boolean,val happyHourPrice:Double?,val happyHourStart:String?,val happyHourEnd:String?,val ageRestricted:Boolean,val minimumAge:Int?)
@Serializable data class IngredientRequest(val name:String,val unit:String,val quantity:Double=0.0,val reorderLevel:Double=0.0,val unitCost:Double=0.0,val purchaseUnit:String?=null,val purchaseUnitSize:Double=1.0)
@Serializable data class IngredientResponse(val id:String,val name:String,val unit:String,val quantity:Double,val reorderLevel:Double,val unitCost:Double,val isLowStock:Boolean,val purchaseUnit:String?=null,val purchaseUnitSize:Double=1.0)
@Serializable data class RecipeLine(val ingredientId:String,val quantity:Double)
@Serializable data class SaveRecipeRequest(val lines:List<RecipeLine>)
@Serializable data class BarStockEventRequest(val productId:String?=null,val ingredientId:String?=null,val eventType:String,val quantity:Double,val unit:String,val reason:String="")
@Serializable data class ShiftOpenRequest(val openingFloat:Double=0.0,val notes:String="")
@Serializable data class ShiftCloseRequest(val actualCash:Double,val actualMpesa:Double?=null,val actualCard:Double?=null,val tipsTotal:Double=0.0,val expensesTotal:Double=0.0,val notes:String="")
@Serializable data class ShiftResponse(val id:String,val openedBy:String,val openedAt:String,val closedAt:String?,val openingFloat:Double,val expectedCash:Double?,val actualCash:Double?,val mpesaTotal:Double?,val cardTotal:Double?,val tipsTotal:Double,val expensesTotal:Double,val status:String,val variance:Double?,val actualMpesa:Double?=null,val actualCard:Double?=null,val mpesaVariance:Double?=null,val cardVariance:Double?=null,val totalVariance:Double?=null)
@Serializable data class SupplierRequest(val name:String,val phone:String="",val email:String?=null,val address:String?=null)
@Serializable data class SupplierResponse(val id:String,val name:String,val phone:String,val email:String?,val address:String?,val isActive:Boolean)
@Serializable data class PurchaseOrderLineRequest(val ingredientId:String,val quantity:Double,val unitCost:Double,val purchaseUnit:String?=null)
@Serializable data class PurchaseOrderRequest(val supplierId:String,val notes:String="",val items:List<PurchaseOrderLineRequest>)
@Serializable data class PurchaseOrderResponse(val id:String,val orderNumber:String,val supplierId:String,val status:String,val totalCost:Double,val orderedAt:String,val receivedAt:String?,val items:List<PurchaseOrderLineResponse> = emptyList())
@Serializable data class ApprovalRequest(val actionType:String,val entityType:String,val entityId:String,val reason:String,val amount:Double?=null,val quantity:Double?=null,val eventType:String?=null)
@Serializable data class ApprovalDecisionRequest(val approved:Boolean)
@Serializable data class ApprovalResponse(val id:String,val actionType:String,val entityType:String,val entityId:String,val requestedBy:String,val approvedBy:String?,val status:String,val reason:String,val requestedAt:String,val amount:Double?=null,val quantity:Double?=null,val eventType:String?=null)
@Serializable data class SplitPaymentLine(val amount:Double,val method:String,val phone:String?=null)
@Serializable data class SplitBillRequest(val payments:List<SplitPaymentLine>)
@Serializable data class HospitalityOperationsResponse(val reservations:List<ReservationResponse>,val menuProfiles:List<MenuProfileResponse>,val ingredients:List<IngredientResponse>,val shifts:List<ShiftResponse>,val suppliers:List<SupplierResponse>,val purchaseOrders:List<PurchaseOrderResponse>,val approvals:List<ApprovalResponse>)
@Serializable data class HospitalityReportResponse(val byWaiter:List<ReportBreakdown>,val byTable:List<ReportBreakdown>,val byItem:List<ReportBreakdown>,val byCategory:List<ReportBreakdown>,val byHour:List<ReportBreakdown>,val byPaymentMethod:List<ReportBreakdown>,val byChannel:List<ReportBreakdown>,val byShift:List<ReportBreakdown>,val byLocation:List<ReportBreakdown>,val foodCost:Double,val beverageCost:Double,val wastageCost:Double,val grossMargin:Double,val averageTableTurnoverMinutes:Double)

@Serializable data class IngredientPurchaseUnitRequest(val purchaseUnit:String?,val purchaseUnitSize:Double=1.0)
@Serializable data class PurchaseOrderLineResponse(val ingredientId:String,val ingredientName:String,val stockUnit:String,val purchaseQuantity:Double,val purchaseUnit:String,val purchaseUnitCost:Double,val conversionFactor:Double,val stockQuantity:Double,val stockUnitCost:Double)
@Serializable data class StaffShiftRequest(val notes:String="")
@Serializable data class StaffShiftResponse(val id:String,val userId:String,val openedAt:String,val closedAt:String?,val status:String,val notes:String,val userName:String="",val summary:StaffShiftSummary=StaffShiftSummary())
@Serializable data class BillHandoverRequest(val orderIds:List<String>,val toUserId:String,val notes:String="")
@Serializable data class BillHandoverDecisionRequest(val action:String)
@Serializable data class BillHandoverResponse(val id:String,val orderId:String,val orderNumber:String,val fromUserId:String,val fromUserName:String,val toUserId:String,val toUserName:String,val requestedBy:String,val status:String,val notes:String,val balanceAtRequest:Double,val requestedAt:String,val decidedAt:String?)
@Serializable data class HandoverStaffResponse(val id:String,val name:String,val onDuty:Boolean)
@Serializable data class HospitalityDutyResponse(val shift:StaffShiftResponse?,val staff:List<HandoverStaffResponse>,val handovers:List<BillHandoverResponse>,val ownedOpenOrderIds:List<String>,val recentShifts:List<StaffShiftResponse> = emptyList())

@Serializable data class StaffCompletedOrder(val id:String,val orderNumber:String,val amount:Double,val completedAt:String,val involvement:String)
@Serializable data class StaffShiftSummary(val completedOrderCount:Int=0,val completedOrderTotal:Double=0.0,val servedOrderCount:Int=0,val settledOrderCount:Int=0,val cashTotal:Double=0.0,val mpesaTotal:Double=0.0,val cardTotal:Double=0.0,val otherTotal:Double=0.0,val collectedTotal:Double=0.0,val handedOverCount:Int=0,val receivedBillCount:Int=0,val completedOrders:List<StaffCompletedOrder> = emptyList())
