package com.app.biashara.services

import com.app.biashara.auth.generateId
import com.app.biashara.db.*
import com.app.biashara.models.*
import kotlinx.datetime.Clock
import kotlinx.datetime.Instant
import kotlinx.datetime.LocalDate
import kotlinx.datetime.DateTimeUnit
import kotlinx.datetime.TimeZone
import kotlinx.datetime.atStartOfDayIn
import kotlinx.datetime.plus
import kotlinx.datetime.toLocalDateTime
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import org.jetbrains.exposed.sql.*
import org.jetbrains.exposed.sql.statements.UpdateBuilder
import org.jetbrains.exposed.sql.SqlExpressionBuilder.eq
import org.jetbrains.exposed.sql.transactions.transaction

class AdvancedHospitalityService {
    private val json=Json { ignoreUnknownKeys=true }

    fun dashboard(businessId:String)=transaction { HospitalityOperationsResponse(reservations(businessId),menuProfiles(businessId),ingredients(businessId),shifts(businessId),suppliers(businessId),purchaseOrders(businessId),approvals(businessId)) }

    fun saveReservation(businessId:String,userId:String,request:ReservationRequest)=transaction {
        require(request.customerName.trim().isNotBlank()){"Customer name is required"}; require(request.guestCount in 1..100){"Guest count must be between 1 and 100"}
        val at=Instant.parse(request.reservedAt);val durationMinutes=request.durationMinutes.coerceIn(15,1440);request.tableId?.let { id -> require(HospitalityTablesTable.select{(HospitalityTablesTable.id eq id) and (HospitalityTablesTable.businessId eq businessId) and (HospitalityTablesTable.isActive eq true)}.any()){"Table not found"};val requestedEnd=at.plus(durationMinutes.toLong(),DateTimeUnit.MINUTE);val overlaps=HospitalityReservationsTable.select{(HospitalityReservationsTable.businessId eq businessId) and (HospitalityReservationsTable.tableId eq id) and (HospitalityReservationsTable.status inList listOf("BOOKED","SEATED")) and (HospitalityReservationsTable.reservedAt less requestedEnd)}.any{row->row[HospitalityReservationsTable.reservedAt].plus(row[HospitalityReservationsTable.durationMinutes].toLong(),DateTimeUnit.MINUTE)>at};require(!overlaps){"Table is already reserved for that time"} }
        val id=generateId(); val now=Clock.System.now(); HospitalityReservationsTable.insert { it[HospitalityReservationsTable.id]=id;it[HospitalityReservationsTable.businessId]=businessId;it[tableId]=request.tableId;it[customerName]=request.customerName.trim();it[customerPhone]=request.customerPhone.trim();it[guestCount]=request.guestCount;it[reservedAt]=at;it[HospitalityReservationsTable.durationMinutes]=durationMinutes;it[status]="BOOKED";it[notes]=request.notes.take(500);it[createdAt]=now;it[updatedAt]=now }; audit(businessId,userId,"RESERVATION_CREATED","RESERVATION",id); reservations(businessId).first{it.id==id}
    }
    fun updateReservationStatus(businessId:String,userId:String,id:String,status:String)=transaction { val value=status.uppercase();require(value in setOf("BOOKED","SEATED","COMPLETED","CANCELLED","NO_SHOW")){"Invalid reservation status"};val current=HospitalityReservationsTable.select{(HospitalityReservationsTable.id eq id) and (HospitalityReservationsTable.businessId eq businessId)}.firstOrNull()?:error("Reservation not found");val allowed=when(current[HospitalityReservationsTable.status]){"BOOKED"->setOf("BOOKED","SEATED","CANCELLED","NO_SHOW");"SEATED"->setOf("SEATED","COMPLETED");else->setOf(current[HospitalityReservationsTable.status])};require(value in allowed){"Cannot change a ${current[HospitalityReservationsTable.status].lowercase()} reservation to $value"};require(HospitalityReservationsTable.update({(HospitalityReservationsTable.id eq id) and (HospitalityReservationsTable.businessId eq businessId)}){it[HospitalityReservationsTable.status]=value;it[updatedAt]=Clock.System.now()}==1){"Reservation not found"};audit(businessId,userId,"RESERVATION_$value","RESERVATION",id);reservations(businessId).first{it.id==id} }
    fun updateTableOperations(businessId:String,userId:String,id:String,r:TableOperationsRequest)=transaction {
        require(r.positionX==null||r.positionX>=0){"Table X position cannot be negative"};require(r.positionY==null||r.positionY>=0){"Table Y position cannot be negative"};require(r.shape==null||r.shape.uppercase() in setOf("RECTANGLE","CIRCLE")){"Invalid table shape"}
        r.waiterUserId?.let { require(UsersTable.select{(UsersTable.id eq it) and (UsersTable.businessId eq businessId) and (UsersTable.isActive eq true)}.any()){"Waiter not found"} }
        r.mergeIntoTableId?.let { require(it!=id){"A table cannot be merged into itself"};require(HospitalityTablesTable.select{(HospitalityTablesTable.id eq it) and (HospitalityTablesTable.businessId eq businessId) and (HospitalityTablesTable.isActive eq true) and HospitalityTablesTable.mergedIntoTableId.isNull()}.any()){"Merge target not found"} }
        require(HospitalityTablesTable.update({(HospitalityTablesTable.id eq id) and (HospitalityTablesTable.businessId eq businessId)}){it[waiterUserId]=r.waiterUserId;it[mergedIntoTableId]=r.mergeIntoTableId;r.positionX?.let{v->it[positionX]=v};r.positionY?.let{v->it[positionY]=v};r.shape?.let{v->it[shape]=v.uppercase()};it[updatedAt]=Clock.System.now()}==1){"Table not found"}
        if(r.mergeIntoTableId!=null) OrdersTable.update({(OrdersTable.businessId eq businessId) and (OrdersTable.hospitalityTableId eq id) and (OrdersTable.tabStatus inList HospitalityService.ACTIVE_TAB_STATUSES)}){it[hospitalityTableId]=r.mergeIntoTableId;it[updatedAt]=Clock.System.now()}
        audit(businessId,userId,"TABLE_OPERATIONS_UPDATED","TABLE",id)
    }
    fun saveMenuProfile(businessId:String,userId:String,productId:String,r:MenuProfileRequest)=transaction {
        require(ProductsTable.select{(ProductsTable.id eq productId) and (ProductsTable.businessId eq businessId)}.any()){"Product not found"};require(!r.ageRestricted || (r.minimumAge?:0) in 18..100){"Minimum age must be at least 18"};require(r.happyHourPrice==null||r.happyHourPrice>=0){"Happy-hour price cannot be negative"};val comboIds=r.comboProductIds.distinct();require(comboIds.isEmpty()||ProductsTable.select{(ProductsTable.businessId eq businessId) and (ProductsTable.id inList comboIds)}.count().toInt()==comboIds.size){"Combo product not found"}
        val exists=HospitalityMenuProfilesTable.select{HospitalityMenuProfilesTable.productId eq productId}.any();val write:HospitalityMenuProfilesTable.(UpdateBuilder<*>) -> Unit = { row -> row[HospitalityMenuProfilesTable.businessId]=businessId;row[preparationStation]=r.preparationStation?.uppercase();row[mealPeriods]=r.mealPeriods.joinToString(",");row[sizesJson]=json.encodeToString(r.sizes);row[extrasJson]=json.encodeToString(r.extras);row[variantsJson]=json.encodeToString(r.variants);row[comboJson]=json.encodeToString(r.comboProductIds);row[soldOut]=r.soldOut;row[happyHourPrice]=r.happyHourPrice;row[happyHourStart]=r.happyHourStart;row[happyHourEnd]=r.happyHourEnd;row[ageRestricted]=r.ageRestricted;row[minimumAge]=r.minimumAge;row[updatedAt]=Clock.System.now() }
        if(exists) HospitalityMenuProfilesTable.update({HospitalityMenuProfilesTable.productId eq productId}){write(it)} else HospitalityMenuProfilesTable.insert{it[HospitalityMenuProfilesTable.productId]=productId;write(it)};audit(businessId,userId,"MENU_PROFILE_SAVED","PRODUCT",productId);menuProfiles(businessId).first{it.productId==productId}
    }
    fun createIngredient(businessId:String,userId:String,r:IngredientRequest)=transaction { require(r.name.trim().isNotBlank()&&r.unit.trim().isNotBlank()){"Ingredient name and unit are required"};require(r.quantity>=0&&r.reorderLevel>=0&&r.unitCost>=0){"Ingredient quantities, reorder level, and cost cannot be negative"};val id=generateId();val now=Clock.System.now();InventoryIngredientsTable.insert{it[InventoryIngredientsTable.id]=id;it[InventoryIngredientsTable.businessId]=businessId;it[name]=r.name.trim();it[unit]=r.unit.uppercase();it[quantity]=r.quantity;it[reorderLevel]=r.reorderLevel;it[unitCost]=r.unitCost;it[isActive]=true;it[createdAt]=now;it[updatedAt]=now};audit(businessId,userId,"INGREDIENT_CREATED","INGREDIENT",id);ingredients(businessId).first{it.id==id} }
    fun saveRecipe(businessId:String,userId:String,productId:String,r:SaveRecipeRequest)=transaction { require(ProductsTable.select{(ProductsTable.id eq productId) and (ProductsTable.businessId eq businessId)}.any()){"Product not found"};require(r.lines.all{it.quantity>0}){"Recipe quantities must be positive"};val ids=r.lines.map{it.ingredientId}.distinct();require(ids.isEmpty()||InventoryIngredientsTable.select{(InventoryIngredientsTable.businessId eq businessId) and (InventoryIngredientsTable.id inList ids)}.count().toInt()==ids.size){"Invalid ingredient"};ProductRecipesTable.deleteWhere{ProductRecipesTable.productId eq productId};r.lines.forEach{line->ProductRecipesTable.insert{it[ProductRecipesTable.productId]=productId;it[ingredientId]=line.ingredientId;it[quantity]=line.quantity}};audit(businessId,userId,"RECIPE_SAVED","PRODUCT",productId);r.lines }
    fun recordBarEvent(businessId:String,userId:String,r:BarStockEventRequest)=transaction { val type=r.eventType.uppercase();require(type in setOf("OPEN_BOTTLE","SHOT","WASTAGE","BREAKAGE","SPILLAGE","COMPLIMENTARY","STOCK_IN","VARIANCE")){"Invalid bar event"};require(r.quantity>0){"Quantity must be positive"};require(r.productId!=null||r.ingredientId!=null){"A product or ingredient is required"};r.productId?.let{id->require(ProductsTable.select{(ProductsTable.id eq id) and (ProductsTable.businessId eq businessId)}.any()){"Product not found"}};val delta=if(type=="STOCK_IN")r.quantity else -r.quantity;r.ingredientId?.let{id->require(InventoryIngredientsTable.update({(InventoryIngredientsTable.id eq id) and (InventoryIngredientsTable.businessId eq businessId)}){with(SqlExpressionBuilder){it.update(quantity,quantity+delta)};it[updatedAt]=Clock.System.now()}==1){"Ingredient not found"}};val id=generateId();BarStockEventsTable.insert{it[BarStockEventsTable.id]=id;it[BarStockEventsTable.businessId]=businessId;it[productId]=r.productId;it[ingredientId]=r.ingredientId;it[eventType]=type;it[quantity]=r.quantity;it[unit]=r.unit.uppercase();it[reason]=r.reason.take(500);it[recordedBy]=userId;it[recordedAt]=Clock.System.now()};audit(businessId,userId,"BAR_$type","BAR_STOCK_EVENT",id);id }
    fun openShift(businessId:String,userId:String,r:ShiftOpenRequest)=transaction { require(r.openingFloat>=0){"Opening float cannot be negative"};require(HospitalityShiftsTable.select{(HospitalityShiftsTable.businessId eq businessId) and (HospitalityShiftsTable.status eq "OPEN")}.none()){"A shift is already open"};val id=generateId();HospitalityShiftsTable.insert{it[HospitalityShiftsTable.id]=id;it[HospitalityShiftsTable.businessId]=businessId;it[openedBy]=userId;it[openedAt]=Clock.System.now();it[openingFloat]=r.openingFloat;it[tipsTotal]=0.0;it[expensesTotal]=0.0;it[status]="OPEN";it[notes]=r.notes.take(500)};audit(businessId,userId,"SHIFT_OPENED","SHIFT",id);shifts(businessId).first{it.id==id} }
    fun closeShift(businessId:String,userId:String,id:String,r:ShiftCloseRequest)=transaction { require(r.actualCash>=0&&r.tipsTotal>=0&&r.expensesTotal>=0){"Cash, tips, and expenses cannot be negative"};val shift=HospitalityShiftsTable.select{(HospitalityShiftsTable.id eq id) and (HospitalityShiftsTable.businessId eq businessId) and (HospitalityShiftsTable.status eq "OPEN")}.firstOrNull()?:error("Open shift not found");val payments=PaymentsTable.select{(PaymentsTable.businessId eq businessId) and (PaymentsTable.transactionDate greaterEq shift[HospitalityShiftsTable.openedAt]) and (PaymentsTable.status eq "SUCCESS")}.toList();val cash=payments.filter{it[PaymentsTable.method]=="CASH"}.sumOf{it[PaymentsTable.amount]};val mpesa=payments.filter{it[PaymentsTable.method]=="MPESA"}.sumOf{it[PaymentsTable.amount]};val card=payments.filter{it[PaymentsTable.method]=="CARD"}.sumOf{it[PaymentsTable.amount]};val expected=shift[HospitalityShiftsTable.openingFloat]+cash-r.expensesTotal;HospitalityShiftsTable.update({HospitalityShiftsTable.id eq id}){it[closedBy]=userId;it[closedAt]=Clock.System.now();it[expectedCash]=expected;it[actualCash]=r.actualCash;it[mpesaTotal]=mpesa;it[cardTotal]=card;it[tipsTotal]=r.tipsTotal;it[expensesTotal]=r.expensesTotal;it[status]="CLOSED";it[notes]=r.notes.take(500)};audit(businessId,userId,"SHIFT_CLOSED","SHIFT",id,"{\"variance\":${r.actualCash-expected}}");shifts(businessId).first{it.id==id} }
    fun createSupplier(businessId:String,userId:String,r:SupplierRequest)=transaction { require(r.name.trim().isNotBlank()){"Supplier name is required"};val id=generateId();val now=Clock.System.now();SuppliersTable.insert{it[SuppliersTable.id]=id;it[SuppliersTable.businessId]=businessId;it[name]=r.name.trim();it[phone]=r.phone.trim();it[email]=r.email;it[address]=r.address;it[isActive]=true;it[createdAt]=now;it[updatedAt]=now};audit(businessId,userId,"SUPPLIER_CREATED","SUPPLIER",id);suppliers(businessId).first{it.id==id} }
    fun createPurchaseOrder(businessId:String,userId:String,r:PurchaseOrderRequest)=transaction { require(SuppliersTable.select{(SuppliersTable.id eq r.supplierId) and (SuppliersTable.businessId eq businessId)}.any()){"Supplier not found"};require(r.items.isNotEmpty()&&r.items.all{it.quantity>0&&it.unitCost>=0}){"Valid purchase items are required"};val ingredientIds=r.items.map{it.ingredientId}.distinct();require(InventoryIngredientsTable.select{(InventoryIngredientsTable.businessId eq businessId) and (InventoryIngredientsTable.id inList ingredientIds)}.count().toInt()==ingredientIds.size){"Ingredient not found"};val id=generateId();val now=Clock.System.now();val number="PO-${now.toEpochMilliseconds().toString().takeLast(8)}";val total=r.items.sumOf{it.quantity*it.unitCost};PurchaseOrdersTable.insert{it[PurchaseOrdersTable.id]=id;it[PurchaseOrdersTable.businessId]=businessId;it[supplierId]=r.supplierId;it[orderNumber]=number;it[status]="ORDERED";it[orderedAt]=now;it[totalCost]=total;it[notes]=r.notes.take(500);it[createdBy]=userId};r.items.forEach{line->PurchaseOrderItemsTable.insert{it[PurchaseOrderItemsTable.id]=generateId();it[purchaseOrderId]=id;it[ingredientId]=line.ingredientId;it[orderedQuantity]=line.quantity;it[receivedQuantity]=0.0;it[unitCost]=line.unitCost}};audit(businessId,userId,"PURCHASE_ORDER_CREATED","PURCHASE_ORDER",id);purchaseOrders(businessId).first{it.id==id} }
    fun receivePurchaseOrder(businessId:String,userId:String,id:String)=transaction { val po=PurchaseOrdersTable.select{(PurchaseOrdersTable.id eq id) and (PurchaseOrdersTable.businessId eq businessId) and (PurchaseOrdersTable.status neq "RECEIVED")}.firstOrNull()?:error("Purchase order not found or already received");PurchaseOrderItemsTable.select{PurchaseOrderItemsTable.purchaseOrderId eq id}.forEach{line->require(InventoryIngredientsTable.update({(InventoryIngredientsTable.id eq line[PurchaseOrderItemsTable.ingredientId]) and (InventoryIngredientsTable.businessId eq businessId)}){with(SqlExpressionBuilder){it.update(quantity,quantity+line[PurchaseOrderItemsTable.orderedQuantity])};it[unitCost]=line[PurchaseOrderItemsTable.unitCost];it[updatedAt]=Clock.System.now()}==1){"Ingredient not found"};PurchaseOrderItemsTable.update({PurchaseOrderItemsTable.id eq line[PurchaseOrderItemsTable.id]}){it[receivedQuantity]=line[PurchaseOrderItemsTable.orderedQuantity]}};PurchaseOrdersTable.update({PurchaseOrdersTable.id eq po[PurchaseOrdersTable.id]}){it[status]="RECEIVED";it[receivedAt]=Clock.System.now()};audit(businessId,userId,"PURCHASE_ORDER_RECEIVED","PURCHASE_ORDER",id);purchaseOrders(businessId).first{it.id==id} }
    fun requestApproval(businessId:String,userId:String,r:ApprovalRequest)=transaction { val id=generateId();ManagerApprovalsTable.insert{it[ManagerApprovalsTable.id]=id;it[ManagerApprovalsTable.businessId]=businessId;it[actionType]=r.actionType.uppercase();it[entityType]=r.entityType.uppercase();it[entityId]=r.entityId;it[requestedBy]=userId;it[status]="PENDING";it[reason]=r.reason.take(500);it[requestedAt]=Clock.System.now()};audit(businessId,userId,"APPROVAL_REQUESTED",r.entityType,id);approvals(businessId).first{it.id==id} }
    fun decideApproval(businessId:String,userId:String,id:String,approved:Boolean)=transaction { require(ManagerApprovalsTable.update({(ManagerApprovalsTable.id eq id) and (ManagerApprovalsTable.businessId eq businessId) and (ManagerApprovalsTable.status eq "PENDING")}){it[approvedBy]=userId;it[status]=if(approved)"APPROVED" else "REJECTED";it[decidedAt]=Clock.System.now()}==1){"Pending approval not found"};audit(businessId,userId,if(approved)"APPROVAL_GRANTED" else "APPROVAL_REJECTED","APPROVAL",id);approvals(businessId).first{it.id==id} }
    fun splitBill(businessId:String,userId:String,orderId:String,r:SplitBillRequest)=transaction {
        val order=OrdersTable.select{
            (OrdersTable.id eq orderId) and (OrdersTable.businessId eq businessId) and
                (OrdersTable.serviceType neq "RETAIL") and (OrdersTable.tabStatus inList HospitalityService.ACTIVE_TAB_STATUSES)
        }.firstOrNull()?:error("Active hospitality tab not found")
        require(OrderSplitPaymentsTable.select{OrderSplitPaymentsTable.orderId eq orderId}.none()){"This tab has already been split"}
        require(r.payments.size>=2){"At least two payment lines are required"}
        require(r.payments.all{it.amount>0&&it.method.equals("CASH",true)}){"Only verified cash split payments are currently supported"}
        require(kotlin.math.abs(r.payments.sumOf{it.amount}-order[OrdersTable.subtotal])<0.01){"Split payments must equal the order total"}
        val now=Clock.System.now()
        r.payments.forEach{line->
            OrderSplitPaymentsTable.insert{it[id]=generateId();it[OrderSplitPaymentsTable.businessId]=businessId;it[OrderSplitPaymentsTable.orderId]=orderId;it[amount]=line.amount;it[method]="CASH";it[status]="SUCCESS";it[createdBy]=userId;it[createdAt]=now}
            PaymentsTable.insert{it[id]=generateId();it[PaymentsTable.businessId]=businessId;it[PaymentsTable.orderId]=orderId;it[transactionCode]="SPLIT-CASH-${generateId().take(8)}";it[amount]=line.amount;it[payerPhone]=line.phone.orEmpty();it[payerName]=order[OrdersTable.customerName];it[method]="CASH";it[status]="SUCCESS";it[channel]="HOSPITALITY_SPLIT";it[reconciled]=true;it[transactionDate]=now}
        }
        OrdersTable.update({OrdersTable.id eq orderId}){it[paymentMethod]="SPLIT";it[paymentStatus]="PAID";it[deliveryStatus]="DELIVERED";it[tabStatus]="CLOSED";it[updatedAt]=now}
        order[OrdersTable.hospitalityTableId]?.let{tableId->
            val another=OrdersTable.select{(OrdersTable.businessId eq businessId) and (OrdersTable.hospitalityTableId eq tableId) and (OrdersTable.id neq orderId) and (OrdersTable.tabStatus inList HospitalityService.ACTIVE_TAB_STATUSES)}.any()
            if(!another)HospitalityTablesTable.update({(HospitalityTablesTable.id eq tableId) and (HospitalityTablesTable.businessId eq businessId)}){it[status]="AVAILABLE";it[updatedAt]=now}
        }
        audit(businessId,userId,"BILL_SPLIT","ORDER",orderId);r.payments
    }
    fun report(businessId:String,startDate:String,endDate:String)=transaction {
        val zone=TimeZone.of("Africa/Nairobi");val start=LocalDate.parse(startDate).atStartOfDayIn(zone);val end=LocalDate.parse(endDate).plus(1,DateTimeUnit.DAY).atStartOfDayIn(zone)
        val orders=OrdersTable.select{(OrdersTable.businessId eq businessId) and (OrdersTable.serviceType neq "RETAIL") and (OrdersTable.createdAt greaterEq start) and (OrdersTable.createdAt less end)}.toList();val ids=orders.map{it[OrdersTable.id]};val items=if(ids.isEmpty())emptyList() else OrderItemsTable.select{OrderItemsTable.orderId inList ids}.toList();val products=if(items.isEmpty())emptyMap() else ProductsTable.select{ProductsTable.id inList items.map{it[OrderItemsTable.productId]}}.associateBy{it[ProductsTable.id]};val users=UsersTable.select{UsersTable.businessId eq businessId}.associate{it[UsersTable.id] to it[UsersTable.name]};val tables=HospitalityTablesTable.select{HospitalityTablesTable.businessId eq businessId}.associate{it[HospitalityTablesTable.id] to it[HospitalityTablesTable.name]}
        fun orderBreakdown(key:(ResultRow)->String)=orders.groupBy(key).map{(label,rows)->ReportBreakdown(label,rows.size,rows.sumOf{it[OrdersTable.subtotal]})}.sortedByDescending{it.amount}
        fun itemBreakdown(key:(ResultRow)->String)=items.groupBy(key).map{(label,rows)->ReportBreakdown(label,rows.sumOf{it[OrderItemsTable.quantity]},rows.sumOf{it[OrderItemsTable.quantity]*it[OrderItemsTable.unitPrice]-it[OrderItemsTable.discountAmount]})}.sortedByDescending{it.amount}
        var food=0.0;var beverage=0.0;items.forEach{item->val recipe=ProductRecipesTable.select{ProductRecipesTable.productId eq item[OrderItemsTable.productId]};val cost=recipe.sumOf{line->val ingredient=InventoryIngredientsTable.select{InventoryIngredientsTable.id eq line[ProductRecipesTable.ingredientId]}.firstOrNull();line[ProductRecipesTable.quantity]*(ingredient?.get(InventoryIngredientsTable.unitCost)?:0.0)*item[OrderItemsTable.quantity]};if(hospitalityStationFor(products[item[OrderItemsTable.productId]]?.get(ProductsTable.category).orEmpty())=="BAR")beverage+=cost else food+=cost}
        val waste=BarStockEventsTable.select{(BarStockEventsTable.businessId eq businessId) and (BarStockEventsTable.recordedAt greaterEq start) and (BarStockEventsTable.recordedAt less end) and (BarStockEventsTable.eventType inList listOf("WASTAGE","BREAKAGE","SPILLAGE"))}.sumOf{event->event[BarStockEventsTable.quantity]*(event[BarStockEventsTable.ingredientId]?.let{id->InventoryIngredientsTable.select{InventoryIngredientsTable.id eq id}.firstOrNull()?.get(InventoryIngredientsTable.unitCost)}?:0.0)}
        val revenue=orders.sumOf{it[OrdersTable.subtotal]};val closed=orders.filter{it[OrdersTable.tabStatus]=="CLOSED"};val turnover=if(closed.isEmpty())0.0 else closed.map{(it[OrdersTable.updatedAt].toEpochMilliseconds()-it[OrdersTable.createdAt].toEpochMilliseconds())/60000.0}.average();val shiftRows=HospitalityShiftsTable.select{(HospitalityShiftsTable.businessId eq businessId) and (HospitalityShiftsTable.openedAt less end)}.toList()
        HospitalityReportResponse(orderBreakdown{users[it[OrdersTable.serverUserId]]?:"Unassigned"},orderBreakdown{tables[it[OrdersTable.hospitalityTableId]]?:it[OrdersTable.serviceType]},itemBreakdown{it[OrderItemsTable.productName]},itemBreakdown{products[it[OrderItemsTable.productId]]?.get(ProductsTable.category)?.ifBlank{"Uncategorised"}?:"Uncategorised"},orderBreakdown{"${it[OrdersTable.createdAt].toLocalDateTime(zone).hour.toString().padStart(2,'0')}:00"},orderBreakdown{it[OrdersTable.paymentMethod]},orderBreakdown{it[OrdersTable.salesChannel]},orderBreakdown{o->shiftRows.firstOrNull{s->o[OrdersTable.createdAt]>=s[HospitalityShiftsTable.openedAt]&&(s[HospitalityShiftsTable.closedAt]?.let{o[OrdersTable.createdAt]<it}?:true)}?.get(HospitalityShiftsTable.id)?.take(8)?:"No shift"},orderBreakdown{it[OrdersTable.serviceType]},food,beverage,waste,if(revenue>0)(revenue-food-beverage-waste)/revenue*100 else 0.0,turnover)
    }

    private fun reservations(b:String)=HospitalityReservationsTable.select{HospitalityReservationsTable.businessId eq b}.orderBy(HospitalityReservationsTable.reservedAt).map{ReservationResponse(it[HospitalityReservationsTable.id],it[HospitalityReservationsTable.tableId],it[HospitalityReservationsTable.customerName],it[HospitalityReservationsTable.customerPhone],it[HospitalityReservationsTable.guestCount],it[HospitalityReservationsTable.reservedAt].toString(),it[HospitalityReservationsTable.durationMinutes],it[HospitalityReservationsTable.status],it[HospitalityReservationsTable.notes])}
    private fun menuProfiles(b:String)=HospitalityMenuProfilesTable.select{HospitalityMenuProfilesTable.businessId eq b}.map{MenuProfileResponse(it[HospitalityMenuProfilesTable.productId],it[HospitalityMenuProfilesTable.preparationStation],it[HospitalityMenuProfilesTable.mealPeriods].split(',').filter(String::isNotBlank),json.decodeFromString(it[HospitalityMenuProfilesTable.sizesJson]),json.decodeFromString(it[HospitalityMenuProfilesTable.extrasJson]),json.decodeFromString(it[HospitalityMenuProfilesTable.variantsJson]),json.decodeFromString(it[HospitalityMenuProfilesTable.comboJson]),it[HospitalityMenuProfilesTable.soldOut],it[HospitalityMenuProfilesTable.happyHourPrice],it[HospitalityMenuProfilesTable.happyHourStart],it[HospitalityMenuProfilesTable.happyHourEnd],it[HospitalityMenuProfilesTable.ageRestricted],it[HospitalityMenuProfilesTable.minimumAge])}
    private fun ingredients(b:String)=InventoryIngredientsTable.select{InventoryIngredientsTable.businessId eq b}.orderBy(InventoryIngredientsTable.name).map{IngredientResponse(it[InventoryIngredientsTable.id],it[InventoryIngredientsTable.name],it[InventoryIngredientsTable.unit],it[InventoryIngredientsTable.quantity],it[InventoryIngredientsTable.reorderLevel],it[InventoryIngredientsTable.unitCost],it[InventoryIngredientsTable.quantity]<=it[InventoryIngredientsTable.reorderLevel])}
    private fun shifts(b:String)=HospitalityShiftsTable.select{HospitalityShiftsTable.businessId eq b}.orderBy(HospitalityShiftsTable.openedAt,SortOrder.DESC).map{val expected=it[HospitalityShiftsTable.expectedCash];val actual=it[HospitalityShiftsTable.actualCash];ShiftResponse(it[HospitalityShiftsTable.id],it[HospitalityShiftsTable.openedBy],it[HospitalityShiftsTable.openedAt].toString(),it[HospitalityShiftsTable.closedAt]?.toString(),it[HospitalityShiftsTable.openingFloat],expected,actual,it[HospitalityShiftsTable.mpesaTotal],it[HospitalityShiftsTable.cardTotal],it[HospitalityShiftsTable.tipsTotal],it[HospitalityShiftsTable.expensesTotal],it[HospitalityShiftsTable.status],if(expected!=null&&actual!=null)actual-expected else null)}
    private fun suppliers(b:String)=SuppliersTable.select{SuppliersTable.businessId eq b}.orderBy(SuppliersTable.name).map{SupplierResponse(it[SuppliersTable.id],it[SuppliersTable.name],it[SuppliersTable.phone],it[SuppliersTable.email],it[SuppliersTable.address],it[SuppliersTable.isActive])}
    private fun purchaseOrders(b:String)=PurchaseOrdersTable.select{PurchaseOrdersTable.businessId eq b}.orderBy(PurchaseOrdersTable.orderedAt,SortOrder.DESC).map{PurchaseOrderResponse(it[PurchaseOrdersTable.id],it[PurchaseOrdersTable.orderNumber],it[PurchaseOrdersTable.supplierId],it[PurchaseOrdersTable.status],it[PurchaseOrdersTable.totalCost],it[PurchaseOrdersTable.orderedAt].toString(),it[PurchaseOrdersTable.receivedAt]?.toString())}
    private fun approvals(b:String)=ManagerApprovalsTable.select{ManagerApprovalsTable.businessId eq b}.orderBy(ManagerApprovalsTable.requestedAt,SortOrder.DESC).map{ApprovalResponse(it[ManagerApprovalsTable.id],it[ManagerApprovalsTable.actionType],it[ManagerApprovalsTable.entityType],it[ManagerApprovalsTable.entityId],it[ManagerApprovalsTable.requestedBy],it[ManagerApprovalsTable.approvedBy],it[ManagerApprovalsTable.status],it[ManagerApprovalsTable.reason],it[ManagerApprovalsTable.requestedAt].toString())}
    private fun audit(b:String,u:String,a:String,t:String,id:String?,d:String="{}"){AuditEventsTable.insert{it[AuditEventsTable.id]=generateId();it[businessId]=b;it[userId]=u;it[action]=a;it[entityType]=t;it[entityId]=id;it[details]=d;it[occurredAt]=Clock.System.now()}}
}
